### ISSUE TITLE
Scroll down on space press

### ISSUE THREAD

**Issue by borisrorsvort** [nylas/nylas-mail#1171]
As in mail app or browser based email clients, pressing space scrolls down the page

**Comment by dcrystalj** [comment]
I miss this so much. Even better would be custom shortcut, like j/k or J/K

**Comment by DavidChouinard** [comment]
This partly works. Spacebar does scroll, but requires first explicitly selecting the message content pane.

Might be solved by invoking `focus()` or an empty text selection on the message pane.

**Comment by DavidChouinard** [comment]
For others that might take a look at this: focusing the iframe does correctly scroll, but focusing the non-iframe part of the message list doesn't scroll. Something somewhere is calling `preventDefault()` on window keydown events. (the keyboard shortcut keys logic?)

**Comment by rbetts** [comment]
During my  first-ever use of N1, no keyboard centric way to scroll a long message was my first "hmm" moment (after download, install, sync, login, etc). Even being able to select the message via the keyboard and then `space` would be a welcome addition.
