### ISSUE TITLE
New mail in modal when N1 is in fullscreen

### ISSUE THREAD

**Issue by bilby91** [nylas/nylas-mail#1174]
The current behaviour when composing a new email while in fullscreen (OS X) is to open a new window in fullscreen for the new mail. I think this behaviour is really uncomfortable, I think Mail app does a better job creating a modal view for the new email.

Something like this:

![GitHub Logo](https://dl.dropboxusercontent.com/u/11451775/Screen_Shot_2016-01-31_at_5_44_50_PM.png)

Anyone with the same feeling ?

**Comment by thechild** [comment]
This alone makes n1 in fullscreen mode basically unusable.  Something more like mail would be an awesome improvement.

**Comment by grinich** [comment]
I don't believe we can do this with full screen since we run on Electron.

**Comment by bengotow** [comment]
Another incidence of this in support: https://nylas.zendesk.com/agent/tickets/5500
