### ISSUE TITLE
Mark as read not working / New messages in thread not marked as read unless switched to a different view and back

### ISSUE THREAD

**Issue by koterpillar** [nylas/nylas-mail#1298]
Steps to reproduce:
- Start with an empty inbox.
- Send an email to this account from another address. Click on it, wait for a second for it to be marked as read.
- Send another email to this account with the same subject (so it would go into the same thread in Gmail and N1). Click on it, wait for a second.

Expected results:
- The thread is marked read.

Actual results:
- The thread is not marked read.

A workaround is to select another folder, go back to the inbox and select the thread. It will then be marked as read.

**Comment by mbilker** [comment]
I can reproduce this by pressing <kbd>Escape</kbd> to go back to the main message view, then entering the message view again to trigger it as read.

**Comment by johanbrook** [comment]
I get this too, pretty annoying, even though I've marked the setting to "Mark as read instantly". Or simply switch to another email item and back again.

**Comment by jackiehluo** [comment]
Another incidence: https://github.com/nylas/N1/issues/2693

**Comment by jackiehluo** [comment]
Another incidence: https://nylas.zendesk.com/agent/tickets/5696
