### ISSUE TITLE
Pass plugin's directory to each plugin

### ISSUE THREAD

**Issue by colinking** [nylas/nylas-mail#1509]
I contribute to a plugin for N1, [n1-unsubscribe](https://github.com/colinking/n1-unsubscribe), with @KyleKing, and we've been getting a number of issues about missing icons within our plugin (such as [this](https://github.com/colinking/n1-unsubscribe/issues/8)) -- the reason being that we reference the icons with a path like:

```
return "nylas://n1-unsubscribe/assets/unsubscribe-success@2x.png"
```

This becomes a problem because when the plugin is installed by N1, the name is taken from the directory that the plugin's contents are stored in, and that directory isn't always called `n1-unsubscribe`. For example, GitHub's `Download ZIP` functionality will append the branch name to the name of the repo (so it becomes something like `n1-unsubscribe-master`). 

Would it be possible to pass a global variable to the plugin with the name of it's containing directory? Or could the plugin name from inside of `package.json` be used by N1 behind the scenes to redirect these requests to the right folder on the user's system? Or is there a solution already that we didn't find?

Thanks!

**Comment by mbilker** [comment]
I think a better solution would be to use a plugin's name from its `package.json` to determine the path used in https://github.com/nylas/N1/blob/e0976fde2c7c59570641f98bd6ec93ea91c135b9/src/browser/nylas-protocol-handler.coffee

**Comment by mbilker** [comment]
Currently it tries to find its directory as you said before.
