### ISSUE TITLE
Swipe multiple items at once

### ISSUE THREAD

**Issue by califa** [nylas/nylas-mail#1638]
Users should be able to select multiple emails (w/ the ctrl/cmd/shift keys) and swipe/archive them together. This will make it easier to get to inbox zero rather than having to swipe one by one.

Mailbox for Mac and iOS used to have this feature.

**Comment by bengotow** [comment]
Hey! We don't currently have plans to make swipe gestures work with multiple selection, but in the meantime you can select multiple items and use hot keys, or the buttons in the top bar to triage them all at once.
