### ISSUE TITLE
How to throttle method in SpellcheckComposerExtension

### ISSUE THREAD

**Issue by kevinmickey** [nylas/nylas-mail#1686]
I'm not sure if this belongs on Github or Stackoverflow, but I didn't get any [responses there](http://stackoverflow.com/questions/35977452/how-do-you-throttle-a-static-method-in-reactjs).  I appreciate any kind of help!

I am trying to write a plugin that extends the [spellchecker](https://github.com/nylas/N1/blob/master/internal_packages/composer-spellcheck/lib/spellcheck-composer-extension.es6), and so I started with minimal modifications.  

I imported the underscore library, and tried to throttle the _wrapMisspelledWords function:

```
import _ from 'underscore';
...
export default class SpellcheckComposerExtension extends ComposerExtension {
  ...
  static onContentChanged({editor}) {
    SpellcheckComposerExtension.update(editor);
  }

  static update = (editor) => {
    SpellcheckComposerExtension._unwrapWords(editor);
    SpellcheckComposerExtension._wrapMisspelledWords(editor);
  }

  static _wrapMisspelledWords = _.throttle((editor) => {
    console.log('wrap mispelled words');
    ...
    ...
  }, 2000)
  ...
}
```

It appears to throttle correctly at first, and then seems to get stuck in some loop, constantly repeating output from previous changes.  I have read through another thread (http://stackoverflow.com/questions/23123138/perform-debounce-in-react-js) but can't figure out why this behavior is happening.

(Right now I don't care whether it throttles for each instance or across all instances of the Composer.)
- What operating system are you using?
  Mac OS X El Capitan 10.11.3 
- What version of N1 are you using?
  Version 0.4.14-53cd69b (0.4.14-53cd69b)
- Do you have any third-party plugins installed?
  Just my custom copy of the spellchecker.

**Comment by mbilker** [comment]
Would it be a better idea to throttle the `update` method instead of the `_wrapMisspelledWord` method?

Also, do note https://github.com/nylas/N1/blob/master/internal_packages/composer-spellcheck/lib/spellcheck-composer-extension.es6#L125-L126 that it does stop running the tree walker after it found 30 misspellings.

**Comment by kevinmickey** [comment]
That probably would make sense, so I tried it out, and it still produced this same weird behavior where something is getting stuck in an infinite loop.  It behaves well at first, but then I try typing a bunch of characters quickly, and it throttles that correctly, then goes into this infinite loop.  I see onContentChanged (and the functions it calls) being called every 2000 ms (or whatever I set my throttle period to).  Any debugging tips?

**Comment by kevinmickey** [comment]
I did see the stop at 30 misspellings, but I was thinking of doing checks with an external API call, so I want to throttle checking the entire content.

**Comment by mbilker** [comment]
I understand slowing down the spellchecking process. I know Slack does this through `rx` and `rx-lite` is available through `nylas-exports`.

**Comment by kevinmickey** [comment]
I looked at Rx.Observable.throttle, but I'm not sure how to implement it (what is my observable here?)

OK instead of throttling or debouncing, I decided to wrap the update function in setTimeout(..., 0) in order to debug, and still shows this same issue.

The conditions for entering an infinite loop seem to be:
- there is at least one spelling mistake (so that unwrap and wrap say that they've modified the content)
- the update function is added to the event queue instead of firing immediately (using setTimeout, throttle or debounce)

The contenteditable component (https://github.com/nylas/N1/blob/1b4739335f4452faa720914309c5e6a593db531d/src/components/contenteditable/contenteditable.cjsx#L302-L333) has a mutation observer that is paused while the extensions run, and I think when I add my update to the event queue, it starts listening for mutations before the update can run, causing another mutation to be observed, entering the infinite loop.

Any potential solutions, or tips? Thanks!

**Comment by mbilker** [comment]
That makes sense. The mutation observer should be managed better if this is to be done asynchronously.

**Comment by bengotow** [comment]
Hey folks! Sorry for the delay. @kevinmickey, I think that you're correct—the DOMMutationObserver that the contenteditable uses prevents composer extensions from mutating the DOM asynchronously. Each change triggers a lot of code that eventually results in the extension being re-run.

We're looking to change this soon, because we really want the spellchecker to work more like the autolinker, which uses free cycles in Chromium's run loop to do work, but doesn't impact performance: https://github.com/nylas/N1/blob/master/internal_packages/message-list/lib/autolinker.es6#L46

(requestIdleCallback is awesome, and brand new in Chromium 48!)
