### ISSUE TITLE
UI frozen while an attachment is open

### ISSUE THREAD

**Issue by koterpillar** [nylas/nylas-mail#1716]
When an attachment is open by double-clicking its name in a received message, the main N1 window does not respond to any interaction. This includes opening other messages, switching folders, and selecting menu items. (Menus can be open but selecting items doesn't do anything.) After a while, an "N1 is not responding: Would you like to force close it or keep waiting?" window is shown.

Steps to reproduce:
- Open N1
- Select a message with an attachment
- Double-click the attachment name to open it
- Try to select another message, switch folders, or select File - New message

Expected results:
- Selecting another message, switching folders, creating a new message works.

Actual results:
- Clicking on messages does nothing
- Clicking on folders does nothing
- File menu opens, but New message does nothing
- After a while, an "N1 is not responding: Would you like to force close it or keep waiting?" window is shown.

System:
- What operating system are you using? Arch Linux
- What version of N1 are you using? 0.4.14-53cd69b

**Comment by bengotow** [comment]
Hey @koterpillar —I think we saw a similar issue with Firefox on Linux, where the app would dispatch the open request to the other app, which would block and not return. I'm not sure what the best way to resolve this is, unfortunately. We might need to bump this up to Electron because we're using the standard `shell.openExternal` method to open files in the appropriate app.

**Comment by roramirez** [comment]
I do a test i think something is broken the launch the shell.External.


If replace _shell.openExternal_  work fine.
```diff
--- a/src/window-event-handler.coffee
+++ b/src/window-event-handler.coffee
@@ -194,7 +194,7 @@ class WindowEventHandler
       # *might* apply to http/https as well but it's unclear.
       shell.openExternal(encodeURI(decodeURI(href)))
     else if schema in ['http:', 'https:', 'tel:']
-      shell.openExternal(href)
+      require('child_process').exec('xdg-open ' + href)
 
     return
```

if comment the the preventDefault
```diff
--- a/src/components/evented-iframe.cjsx
+++ b/src/components/evented-iframe.cjsx
@@ -142,7 +142,7 @@ class EventedIFrame extends React.Component
         else
           target.setAttribute('href', "http://#{rawHref}")
 
-      e.preventDefault()
+      #e.preventDefault()
       NylasEnv.windowEventHandler.openLink(target: target)
 
   _isBlacklistedHref: (href) ->
```
Is open into the iframe N1


I can, do it, example in the header the window-event-handler.coffee and openExternal is working.

```shell
s = require('electron').shell
s.openExternal('http://rodrigoramirez.com')
```
maybe is something is broken by React.Component. If execute previus sentences into console of Developers tools too is not working.
