### ISSUE TITLE
Feature Request: Email Google Contacts group

### ISSUE THREAD

**Issue by maraisr** [nylas/nylas-mail#1800]
Is this a plugin I ought to be writing - or is there  a currently standing plugin or way to email to a group based on my google contacts?

I have a group setup in Google Contacts, for which i'd like to email to?

**Comment by bengotow** [comment]
Hey @maraisr — we don't currently expose contact groups, but there's been talk of pulling them from third party services and / or detecting them based on message headers. We'd definitely welcome a plugin that added groups support! It may be on the roadmap eventually. The sync-engine project pulls contacts from Google Contacts but not groups, so it might be interesting to start there!
