### ISSUE TITLE
Hide title bar in fullscreen mode for Windows

### ISSUE THREAD

**Issue by DjLeChuck** [nylas/nylas-mail#1830]
##### What operating system are you using?

Windows 10
##### What version of N1 are you using?

0.4.19
## 

**Bug?**
When I launch N1, the full screen mode is not a real full screen mode.
As you can see on the screenshot, the window height is 100% and do not care about the taskbar (which is always visible, no auto-hide).

![nylas-fullscreen](https://cloud.githubusercontent.com/assets/696780/14064311/003d22e8-f3ff-11e5-965b-f4270717fe99.jpg)

**Comment by EZTEQ** [comment]
Reproducable by me on Windows 10 with version 0.4.33 of N1.
