### ISSUE TITLE
Electron Helper High CPU

### ISSUE THREAD

**Issue by jorenfrielink** [nylas/nylas-mail#2068]
When typing new mails or replies the process "Electron Helper" rises to outrageous high CPU, resulting in a big lag. See attached. I've seen it over a 100%. 

Doesn't happen in every email, but I can't seem to find a consistent issue.

Nylas 0.4.25-a22631a on OSX 10.11.4
This might be related as the cpu goes higher when typing; https://github.com/nylas/N1/issues/895

![screen shot 2016-04-26 at 16 19 27](https://cloud.githubusercontent.com/assets/4737455/14821673/f0b363e8-0bcb-11e6-92d8-5ab9838bcafb.png)

**Comment by mbilker** [comment]
Are you sure it is N1 causing this? Slack also an Electron application. Could you check the path of Electron Helper and see if it is contained in the N1 app bundle.

**Comment by jorenfrielink** [comment]
I'm not sure if this is the data you need, let me know if I can provide more;

/  
/Applications/Nylas N1.app/Contents/Frameworks/Electron
Helper.app/Contents/MacOS/Electron Helper  
/Applications/Nylas N1.app/Contents/Frameworks/Electron
Framework.framework/Versions/A/Electron Framework  
/Applications/Nylas
N1.app/Contents/Frameworks/Squirrel.framework/Versions/A/Squirrel  
/Applications/Nylas
N1.app/Contents/Frameworks/ReactiveCocoa.framework/Versions/A/ReactiveCocoa  
/Applications/Nylas
N1.app/Contents/Frameworks/Mantle.framework/Versions/A/Mantle  
/Applications/Nylas N1.app/Contents/Frameworks/Electron
Framework.framework/Versions/A/Libraries/libnode.dylib  
/Applications/Nylas N1.app/Contents/Frameworks/Electron
Framework.framework/Versions/A/Resources/en.lproj/locale.pak  
/System/Library/Frameworks/CoreMIDI.framework/Versions/A/CoreMIDI  
/usr/lib/libexpat.1.dylib  
/private/var/folders/wh/27v_ht3x32n96jnggg71xs1m0000gn/T/.org.chromium.Chromiu
m.dYL1Ve  
/private/var/folders/wh/27v_ht3x32n96jnggg71xs1m0000gn/T/.org.chromium.Chromiu
m.aPuO4J  
/Users/jorenfrielink/.nylas/edgehill.db-shm  
/Applications/Nylas N1.app/Contents/Resources/app.asar.unpacked/node_modules/k
eytar/build/Release/keytar.node  
/usr/share/icu/icudt55l.dat  
/Applications/Nylas N1.app/Contents/Frameworks/Electron
Framework.framework/Versions/A/Resources/icudtl.dat  
/Applications/Nylas N1.app/Contents/Frameworks/Electron
Framework.framework/Versions/A/Resources/snapshot_blob.bin  
/Applications/Nylas N1.app/Contents/Frameworks/Electron
Framework.framework/Versions/A/Resources/natives_blob.bin  
/Applications/Nylas N1.app/Contents/Frameworks/Electron
Framework.framework/Versions/A/Resources/content_shell.pak  
/private/var/folders/wh/27v_ht3x32n96jnggg71xs1m0000gn/0/com.apple.LaunchServi
ces-134501.csstore  
/System/Library/Fonts/SFNSText-Regular.otf  
/private/var/folders/wh/27v_ht3x32n96jnggg71xs1m0000gn/T/.org.chromium.Chromiu
m.LvGl35  
/Applications/Nylas N1.app/Contents/Resources/app.asar.unpacked/node_modules/p
athwatcher/build/Release/pathwatcher.node  
/Applications/Nylas N1.app/Contents/Resources/app.asar.unpacked/node_modules
/atom-keymap/node_modules/keyboard-layout/build/Release/keyboard-layout-
observer.node  
/Applications/Nylas N1.app/Contents/Resources/app.asar.unpacked/node_modules/s
qlite3/lib/binding/electron-v0.36-darwin-x64/node_sqlite3.node  
/System/Library/Keyboard Layouts/AppleKeyboardLayouts.bundle/Contents/Resource
s/AppleKeyboardLayouts-L.dat  
/System/Library/Caches/com.apple.IntlDataCache.le.kbdx  
/Applications/Nylas N1.app/Contents/Resources/app.asar.unpacked/node_modules/s
pellchecker/build/Release/spellchecker.node  
/System/Library/CoreServices/SystemAppearance.bundle/Contents/Resources/System
Appearance.car  
/System/Library/CoreServices/SystemAppearance.bundle/Contents/Resources/Assets
.car  
/Library/Fonts/Times New Roman.ttf  
/System/Library/Fonts/Helvetica.dfont  
/private/var/folders/wh/27v_ht3x32n96jnggg71xs1m0000gn/T/.org.chromium.Chromiu
m.3PegLj  
/private/var/db/mds/system/mdsDirectory.db  
/private/var/db/mds/messages/se_SecurityMessages  
/System/Library/Fonts/Times.dfont  
/usr/lib/dyld  
/private/var/db/dyld/dyld_shared_cache_x86_64h  
/dev/null  
/dev/null  
/dev/null  
-&gt;0x795253d7f6ffa1c5  
count=2, state=0x12  
-&gt;0x795253d7ef304565  
-&gt;0x795253d7f0006325  
count=0, state=0x8  
-&gt;0x795253d7fab05565  
-&gt;0x795253d7f4f6f925  
-&gt;0x795253d7f5411765  
-&gt;0x795253d7f4f6ea25  
count=0, state=0xa  
/Applications/Nylas N1.app/Contents/Frameworks/Electron
Framework.framework/Versions/A/Resources/icudtl.dat  
/Applications/Nylas N1.app/Contents/Frameworks/Electron
Framework.framework/Versions/A/Resources/snapshot_blob.bin  
/Applications/Nylas N1.app/Contents/Frameworks/Electron
Framework.framework/Versions/A/Resources/natives_blob.bin  
/Applications/Nylas N1.app/Contents/Frameworks/Electron
Framework.framework/Versions/A/Resources/en.lproj/locale.pak  
/Applications/Nylas N1.app/Contents/Frameworks/Electron
Framework.framework/Versions/A/Resources/content_shell.pak  
count=0, state=0xa  
-&gt;0x795253d7efa347e5  
-&gt;0x795253d7efd1a5e5  
-&gt;0x795253d7f5ef1095  
/dev/urandom  
-&gt;0x795253d7f7fb9be5  
/Applications/Nylas N1.app/Contents/Resources/atom.asar  
/private/var/folders/wh/27v_ht3x32n96jnggg71xs1m0000gn/T/.org.chromium.Chromiu
m.dYL1Ve  
/private/var/folders/wh/27v_ht3x32n96jnggg71xs1m0000gn/T/.org.chromium.Chromiu
m.LvGl35  
/private/var/folders/wh/27v_ht3x32n96jnggg71xs1m0000gn/T/.org.chromium.Chromiu
m.aPuO4J  
/Applications/Nylas N1.app/Contents/Resources/app.asar  
/private/var/folders/wh/27v_ht3x32n96jnggg71xs1m0000gn/T/Nylas-N1-10092.10094.
log  
count=0, state=0xa  
/System/Library/CoreServices/SystemAppearance.bundle/Contents/Resources/System
Appearance.car  
/System/Library/CoreServices/SystemAppearance.bundle/Contents/Resources/Assets
.car  
/private/var/folders/wh/27v_ht3x32n96jnggg71xs1m0000gn/T/.org.chromium.Chromiu
m.3PegLj  
/Users/jorenfrielink/.nylas/config.cson  
/Users/jorenfrielink/.nylas/edgehill.db  
/dev/null  
/Users/jorenfrielink/.nylas/keymap.cson  
-&gt;0x795253d7f7fbbf0d  
/Users/jorenfrielink/.nylas/edgehill.db-wal  
/Users/jorenfrielink/.nylas/edgehill.db-shm  

  

I did end the process once while N1 was open and it forced closed N1. Also,
while i'm typing this reply I can see the Electron helper's CPU go up from 1%
to about 14%.

  

(btw, I have about five instances of Electron Helper running that all close
when N1 is closed. Only one has a high CPU.)

On Apr 29 2016, at 3:33 am, Matt Bilker &lt;notifications@github.com&gt;
wrote:  

> Are you sure it is N1 causing this? Slack also an Electron application.
Could you check the path of Electron Helper and see if it is contained in the
N1 app bundle.

>

> —  
You are receiving this because you authored the thread.  
Reply to this email directly or [view it on GitHub](https://github.com/nylas/N
1/issues/2068#issuecomment-215608276)![](https://github.com/notifications/beac
on/AEhJr-__5Fs1Kx5mfct7qHN6KfhvjIczks5p8V__gaJpZM4IQAoG.gif)

**Comment by mbilker** [comment]
Okay so it is N1's Electron Helper. I see something like this on Linux and that is from the worker process that handles fetching data from the Sync Engine so the CPU usage may be that.

**Comment by krosti** [comment]
It's also a consistent issue on my side. I think is something related to the Sync process as well. When the Sync message is in the UI this process comes the CPU high to ~90%.

**Comment by mbilker** [comment]
Yikes. It should be lowered in the latest version due to optimizations across the board.

**Comment by jeffmcneill** [comment]
I've got the same problem on the latest version. I installed Nylas N1 last night, no problems. Connected up three gmail accounts (low volume). Turned on the computer and it started N1, then it pretty much hangs. Processor utlization for Electron Helper (I've seen one and two threads) exceeds 100%. OSX Version 0.4.33-e8f137e (0.4.33-e8f137e).

There were two new mail items that took 10 minutes to download.

**Comment by daniel-nelson** [comment]
I'm just evaluating N1. All I reached was the screen to create an N1 account, and my CPU usage was pegged, fan going full blast, and battery draining due to "electron helper". Quiting N1 solved the problem.

**Comment by bengotow** [comment]
Another user has reported this on ZenDesk: https://nylas.zendesk.com/agent/tickets/4306 ("Random high CPU usage all the time")

**Comment by chriswessels** [comment]
This is the biggest issue preventing me from using Nylas!

Is there an action plan to solve? The whole syncing process seems a bit suspect at the moment.

**Comment by jackiehluo** [comment]
Another incidence: https://nylas.zendesk.com/agent/tickets/5713

**Comment by jackiehluo** [comment]
Another incidence: https://nylas.zendesk.com/agent/tickets/5716

**Comment by TylerBrock** [comment]
I'm having this happen as well. Near 100% all the time even if I let it sit and sync fully. It makes the UI extremely unresponsive to actions. For example, archiving an e-mail does not remove the email from the inbox view until many minutes later (if at all).

**Comment by jasonmelgoza** [comment]
Seeing the issue same here! I noticed this last week after a update. 
<img width="381" alt="screen shot 2016-11-08 at 10 35 33 am" src="https://cloud.githubusercontent.com/assets/89980/20111956/252644de-a59f-11e6-932d-33975fb155ac.png">

**Comment by michalhudecek** [comment]
I can confirm this issue on Windows as well.

**Comment by jstejada** [comment]
merging into #3178
