### ISSUE TITLE
Allow developers to publish updates to plugins

### ISSUE THREAD

**Issue by colinking** [nylas/nylas-mail#2144]
Based on past issues, it looks like you all have considered making more features from the Atom package manager available through N1's plugin system. Is the intention that plugins be deployed in a fashion similar to NPM to some kind of package manager network for N1 plugins? 

In the short term, would it be possible to add some way of checking if a more recent version of a plugin is available? Recently, @bengotow pointed out that Electron made breaking changes, which broke the n1-unsubscribe plugin on recent builds of N1. Everyone using these builds will need to update this plugin, though they may not realize this until they notice that the unsubscribe button is not showing up anymore.

Since all plugins would be on GitHub, would it be possible to poll them to gather the package version from `package.json` and determine if the installed plugin is out of date?

**Comment by bengotow** [comment]
Hey! Thanks for posting this @colinking, and thanks for your work on `N1-unsubscribe`. N1 actually already ships with the `apm` package manager from Atom, and we've done some work to build a package server for it (unfortunately GItHub open sourced the client but it uses their own proprietary backend built on GitHub.) We need to put everything together into a packages view that prompts you to update.

I definitely agree that we can't be breaking plugins like N1-unsubscribe. Going to leave this open until we get this addressed. Stay tuned—

**Comment by KyleKing** [comment]
@bengotow, I made an NPM package that automatically alerts users when an updated plugin release is available and I wanted to share it with the rest of the Nylas Plugin community:

https://github.com/KyleKing/n1pluginupdater

<img width="790" alt="notification" src="https://cloud.githubusercontent.com/assets/3784339/16122128/f35c94b0-33b3-11e6-83eb-25efcb174cf6.png">

It is pretty easy to use and can be added like this to any plugin:

```jsx
const config = require(`${__dirname}/../package.json`); // the path to your package.json
const n1pluginupdater = require('n1pluginupdater');

activate: () => {
  n1pluginupdater.checkForUpdate({
    repositoryName: "your_Github_Repository_Name",
    repositoryOwner: "your_Github_Username",
    currentVersion: config.version,
  });
  // Other code...etc.
}
```

**Comment by KyleKing** [comment]
Just wanted to follow up. Do you think the n1pluginupdater package is a good interim solution to share with other N1 developers?
