### ISSUE TITLE
"Move to folder" doesn't work if new email in the exiting thread. 

### ISSUE THREAD

**Issue by ggbal** [nylas/nylas-mail#2160]
##### What operating system are you using?

OS X 10.11.4
##### What version of N1 are you using?

Version 0.4.33-e8f137e (0.4.33-e8f137e)

**Bug?**
##### Do you have any third-party plugins installed?

No
##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

Office365

The Symptom
1. Move an email or email thread to a folder
2. Receive a new email of that thread (e.g. someone replies that thread)
3. the whole thread shows in the inbox. So far so good.
4. Try to move the thread to the same folder the original thread was in using "move to folder" icon/menu. 
5. The thread is not moved. There is no PUT "folder" command issued in the activity window

Workaround:
for step 4, if you move the thread to a different folder than the one the original thread was in, it works.

Or if your drag the thread to the same folder that the original thread was in, it also works. 

This bug has been there for a while, not just restricted to the current version.

**Comment by saqebakhter** [comment]
Having same issue with Exchange - I opened https://github.com/nylas/N1/issues/1948 a month ago similar to this.

**Comment by ggbal** [comment]
I think it is specific to Exchange/Office365 because of the way how N1 does in gmail. 

In gmail account, the label is attached to all the email in the thread. So if there is a new reply to an existing thread, that email is automatically labeled using the label already attached to the thread. So we you use shortcut "L", is triggers "apply label" which actually means toggle the label. This means if the thread already labeled, "L" will remove that label. This make sense in gmail paradigm. 

However in exchange/O365, the same shortcut "L" means "move to folder". And in exchange/O365, the newly replied email is not automatically put into the folder where the existing thread is in. So if the N1 code still does the "toggle" action just like in gmail vs. move, that will not work in Exchange/O365 paradigm. 

This is what I suspect triggering this bug. 

This bug is the last hurdle making me move completely into N1. "Move to folder" is an important and necessary feature in exchange world since it doesn't have label.

**Comment by saqebakhter** [comment]
Agreed -this fix would make Nylas my main email app.

**Comment by Midgaard** [comment]
Hello. 
I'm running 0.4.47-3a2a94c, and OSX 10.11.3. Experiencing the same problem, did anyone find a fix to this? I am having to use the trackpad to manually grab and move the new email in a thread that has already been filed, in order to move the new email having just arrived. It appears that the keyboard shortcut to move the email responds, but the email is not moved to the folder. 

While it's not a issue that makes it a deal breaker for me (nor should it for anyone else) I think it's mostly an annoying productivity and workflow issue. I am in a high email volume environment and shortcuts are not just a part of life, rather they are an integral part of life. 

Thanks for any guidance.

**Comment by saqebakhter** [comment]
Is there any updates to this bug ? Seems like a rather nasty one...

**Comment by ggbal** [comment]
In the latest Nylas Mail, this bug still exists. Any plan to address this problem?

**Comment by jstejada** [comment]
yes! is this the error you are seeing @ggbal #3308 ? I'm going to merge into that issue

**Comment by thepisu** [comment]
I'm not sure it's a duplicate of #3308 ... I still can move the thread with drag & drop to destination folder, so it seems a bug of the "Move" button in the toolbar...
