### ISSUE TITLE
Automatically convert URLs into links

### ISSUE THREAD

**Issue by colinking** [nylas/nylas-mail#2166]
If you are writing an email, you can highlight a URL and click the "create link" button, which will detect that you are highlighting a link and will automatically offer to convert it into a link.

However, it would be more convenient if upon pasting text into an email where the text is a URL, then it will automatically be converted from text into a link.

Default behavior:
![image](https://cloud.githubusercontent.com/assets/2907397/15094464/ea31e580-1472-11e6-8d0e-7e32943fa1d4.png)

**Comment by jackiehluo** [comment]
Another request: https://nylas.zendesk.com/agent/tickets/5498

**Comment by Asuza** [comment]
@jackiehluo, I'm unable to get to that ticket to see what the request is.
