### ISSUE TITLE
Keyboard shortcut ⌘H to hide the app does not work when focused on message, is not mentioned in menu

### ISSUE THREAD

**Issue by markbao** [nylas/nylas-mail#2305]
Keyboard shortcut <kbd>⌘H</kbd> which is a standard OS X shortcut to hide the app does not work when focused on the message body.
##### Are there any related issues?

No
##### What operating system are you using?

OS X El Capitan
##### What version of N1 are you using?

Version 0.4.40-85cf726 (0.4.40-85cf726)
## 

**Bug?**
##### Do you have any third-party plugins installed?

No
##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

No
##### Is the issue reproducible with a particular attachment, message, signature, etc?

1. Click on a message in the message list.
2. Hit <kbd>⌘H</kbd>
3. See that the app closes.
4. Open up N1 again.
5. Click on the message body on the right pane.
6. Hit <kbd>⌘H</kbd>
7. See that N1 does not hide.

**Comment by bengotow** [comment]
Another user reported a related issue via ZenDesk:

```
Just to let you know the cmd+H shortcut started working yesterday, then it 
stopped working again, then started again. So strange! It's now an 
intermittent issue, working sometimes, not working at other times. However, 
in every case all other windows/applications work fine, it's only Nylas N1 
that can't/won't hide when I press cmd+H. Also, even when it's working the 
keyboard shortcut is not displayed in the menu (as per previous screenshot).
```

Can confirm that in 0.4.47, the `Hide Nylas N1` entry in the application menu does not display the shortcut.
