### ISSUE TITLE
`nylas --background` doesn't open N1 in the background

### ISSUE THREAD

**Issue by 1vasari** [nylas/nylas-mail#2354]
##### Are there any related issues?

Not that I can tell.
##### What operating system are you using?

Ubuntu 16.04
##### What version of N1 are you using?

Nylas N1 0.4.40
## 

**Bug?**
##### Do you have any third-party plugins installed?

No
##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

No
##### Is the issue reproducible with a particular attachment, message, signature, etc?

Probably not.
## 

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?

It used to work correctly here in N1.

**Comment by 1vasari** [comment]
Just to clarify...

I have a startup script that runs `nylas --background`. However, in a recent update, this now brings up the main N1 interface instead of opening in the background.

**Comment by kbarralon** [comment]
Same for me, the program does not start in the background with "nylas --background" (on Ubuntu 16.10).

**Comment by Aletheia-Lothlorien** [comment]
Same here. `nylas --background` in the startup script doesn't open in the background for me on Ubuntu Gnome 16.04, but rather the main interface opens (as if the `--background` option has no effect).

**Comment by amiller27** [comment]
Same problem here, running `nylas-mail --background` opens a window with the "Welcome" image.  Running without the background option works just fine.

Related issues: None
OS: Ubuntu Gnome 17.04
Nylas version: 2.0.14
Third-party plugins: No
Not related to a specific email provider, message, etc.

**Comment by aquintanar** [comment]
Same problem, Ubuntu 17,04 and Nylas Mail 2.0.32

**Comment by nataliethistime** [comment]
Hey guys - any updates on this issue? Not sure if this has been fixed and not updated due to the issue going stale...

**Comment by jerm** [comment]
Headsup: https://github.com/nylas/nylas-mail/issues/3621

**Comment by jerm** [comment]
Recommend you check out the Mailspring fork of Nylas Mail (https://github.com/Foundry376/Mailspring)

https://getmailspring.com/

**Comment by nataliethistime** [comment]
Ahhh gotcha. Cheers for the links.
