### ISSUE TITLE
Suggestion: Autoreply

### ISSUE THREAD

**Issue by felixguerrero12** [nylas/nylas-mail#2429]
**Feature Request?**
##### Does this feature exist in another mail client or tool you use?

https://support.google.com/mail/answer/25922?hl=en

I think it would be interesting to have an offline autoreply on Nylan N1. That way I can keep my clients alerted from what time to what time I will be responding to emails or when I am on vacation. Google has the vacation feature where you can set it specifically for when you go on vacation; URL:https://support.google.com/mail/answer/25922?hl=en

**Comment by Method-X** [comment]
If you're using GMail, you can set this on the web client. It would make for a good Nylas plugin, if it's possible.
