### ISSUE TITLE
"Failed to load config.json. Unexpected token"

### ISSUE THREAD

**Issue by HammyHavoc** [nylas/nylas-mail#2518]
##### Are there any related issues?

No.
##### What operating system are you using?

Windows 10.
##### What version of N1 are you using?

The latest.
## 

**Bug?**
Told that Nylas N1 failed to load config.json due to unexpected token, so can't access my emails. Hoping I don't have to reset my configuration because I've adding 20+ accounts isn't a lot of fun.
##### Do you have any third-party plugins installed?

No.
##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

No.
##### Is the issue reproducible with a particular attachment, message, signature, etc?

Just launching Nylas N1.
...

**Comment by andrewwong97** [comment]
Hey, I've had this issue too. Using Mac OS X El Capital 10.11.5 and around 7 email accounts. The first time I reset it I had to add the email accounts again, set my signatures, I agree it's a pain. Also looked into the `~.nylas/config.json` file, which was completely empty. Maybe this is the issue? Would like to get a contributor on this as soon as possible...

<img width="30%" height="30%" alt="screenshot 2016-06-28 17 05 18" src="https://cloud.githubusercontent.com/assets/7339169/16432372/9e66dc42-3d52-11e6-9ff4-b1a2411ed6f1.png">

**Comment by Artjaazz** [comment]
Me too, the same, happens again after resetting configuration and restarting the computer: https://infinit.io/_/38rYVVq

Soon fix would be appreciated
Art

**Comment by bengotow** [comment]
Hey folks—thanks for reporting this. Typically this error only appears if you've edited the config file manually and broken the formatting, which it sounds like you haven't!

If the file has become empty on it's own, that's definitely a serious bug. I'll take a look and see if we can resolve it in one of the upcoming releases. Sorry for the hassle! Adding accounts again really sucks :-(

**Comment by HammyHavoc** [comment]
Would I be able to copy and paste a config.json file from another PC that I run Nylas N1 on?

**Comment by andrewwong97** [comment]
@HammyHavoc It should work. In the meantime while this is being fixed, I created a copy called backup.json which is an identical copy of config.json, and whenever the error appears I run a local script containing the command "cp backup.json config.json" which replaces the damaged file.

**Comment by Artjaazz** [comment]
Maybe the antivirus? I use Bitdefender and 360 Security

**Comment by jackiehluo** [comment]
Another incidence: https://nylas.zendesk.com/agent/tickets/4558

**Comment by jackiehluo** [comment]
Another incidence: https://twitter.com/manicmarvin/status/752403589935489024

**Comment by Cybolic** [comment]
This has happened several times to me as well (on Ubuntu 15.10 and 16.04), latest today; blank config.json after running for a week or so. Today, N1 also gave the following error after setting everything up again the second time (it blanked again a few minutes after the first setup):
```
Could not call remote function ''. Check that the function signature is correct. Underlying error: ENOSPC: no space left on device, open '/home/cybolic/.nylas/config.json'
Error: Could not call remote function ''. Check that the function signature is correct. Underlying error: ENOSPC: no space left on device, open '/home/cybolic/.nylas/config.json'
    at callFunction (/usr/share/nylas/resources/electron.asar/browser/rpc-server.js:220:11)
    at EventEmitter.<anonymous> (/usr/share/nylas/resources/electron.asar/browser/rpc-server.js:301:5)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:201:7)
    at EventEmitter.<anonymous> (/usr/share/nylas/resources/electron.asar/browser/api/web-contents.js:139:25)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
```
There's 18GB free space on my home/root partition.

**Comment by brooksa321** [comment]
+1, I am also seeing the same problem on Windows 10. "Failed to load "config.json" Unexpected tokern". Happens almost every day.

**Comment by Artjaazz** [comment]
Yep, I've switched to Mailbird for now :/

**Comment by jackiehluo** [comment]
Another incidence: https://nylas.zendesk.com/agent/tickets/5698

**Comment by emorikawa** [comment]
Reported by @GM-Polyakov on Windows: ![image](https://cloud.githubusercontent.com/assets/489001/17867305/f0e0430a-6877-11e6-8538-b5c714d18235.png)

**Comment by laughedelic** [comment]
Same problem. Wiped settings suck. Backing up the config manually also sucks.
- N1 0.4.49-c9c04b7
- OS X 10.11.6

**Comment by surdaft** [comment]
I just encountered this bug as well on Windows 10 Pro v1151 x64 after a bluescreen.
Nylas is version 0.4.49.

Only additional configuration changes I have made via the nylas gui was removing the notification sound and removed the signature from the emails to no longer say 'Sent from Nylas.'

**Comment by jackiehluo** [comment]
We've pushed an update that resolves this issue (0.4.51). Let us know if you run into any bugs!

**Comment by jtflynnz** [comment]
This appears to have reappeared in the latest version (1.5.0); having issues since the version bump, but never previously. Running on Windows 10; can temporarily resolve by resetting the config, but it comes up again on a restart.

**Comment by jstejada** [comment]
@jtflynnz thanks for the report. We are going to look into it!

**Comment by da-am** [comment]
This happened today on 1.5.0 - CentOS 7.3. I've been using N1 for about 3 weeks without problem then got the error on reboot today. Config.json was empty.

**Comment by pratnala** [comment]
Happened to me. config.hson had a bunch of hex 0000's in it. Nylas luckily had .bak files of my old config, so I copied them over.

**Comment by cultavix** [comment]
This happened to me as well, on Windows 10. After a reboot of the machine, I've lost all of my configuration. I click reset, re-added my Gmail account and that works fine. However, when trying to re-add the IMAP/SMTP account I have, it's just saying "unforseen error as ocurrsed"

**Comment by josephus** [comment]
Same problem with the 0x00-padded config.json after Windows 10 reboot. This software so not ready for prime-time.
I wonder what happens to the database when I re-add the account.

**Comment by pierrebeaucamp** [comment]
I encountered this error numerous time on Windows 10. Usually it happens if the computer crashes or if I can't shut down normally (like a forced reset). I didn't encounter this using normal shutdowns or reboots.

I could work around this issue by taking a manual backup of `config.json` in `%USERPROFILE%/.nylas-mail` and re-applying it once I encounter this bug. It doesn't seem to corrupt the database or anything else really.

This might be unrelated, but I had similar issues in WSL if one program had the file open / was watching the file and another program modified it. For example, watching a file with gulp and then checking out the same file using git. This essentially deleted all file contents. Again, this might be unrelated and I don't know much about Windows, but maybe this issue could be cause by nylas watching the file?

**Comment by jstejada** [comment]
thanks for the details! I'm merging into #3382

**Comment by Sheepyhead** [comment]
I'm still experiencing this issue in Windows 10 if my computer has crashed. Seems like the way the config is set up is not very robust, I see no reason it should break like this.

**Comment by DrakeTDL** [comment]
I'm also experiencing the same problem, it's really annoying especially when you have to re-add 10+ accounts
@cultavix you can get to the config.json file by going to "C:\Users\\[username]\\.nylas-mail"

**Comment by Artjaazz** [comment]
Hey, I think this issue happens when there's very limited space available on the Disk with the system.
What do you think, guys, who else have limited disk space and this issue?

**Comment by Sheepyhead** [comment]
@Artjaazz Nope, got plenty of space on mine. What I suspect is happening is that the program keeps the config.json file in an unsafe state while running, instead of opening and closing it only when modifications need to be made. This seems like an avoidable issue.

**Comment by paulomanrique** [comment]
Same problem here, Windows 10, 2 days in a row =\

**Comment by jmclemore65** [comment]
I rebooted and for some reason it's working fine now. I wish I could reverse the thread order. Drives me nuts having the latest on the bottom.

**Comment by jmclemore65** [comment]
Okay. It's failing again. Your reply notice thru this thread came in on top so did several others. Now they're going to the bottom again. This seems like an easy fix. Really annoying to have to scroll around to just find my latest email. Deal breaker. What gives?

**Comment by pratnala** [comment]
Nylas is not even being developed anymore. Pointless trying to bother with this.

**Comment by pratnala** [comment]
#3564

**Comment by jmclemore65** [comment]
Wow. I didn't realize that. Thanks! :)
