### ISSUE TITLE
Support for name/email formatted addresses in mail merge

### ISSUE THREAD

**Issue by corneliusio** [nylas/nylas-mail#2624]
**OSX 10.11.5 - N1 Version: 0.4.45-7637265**

Whenever using mail merge, recipient emails can't be formatted with a name, though this formatting is fully supported otherwise. _(e.g._ `John Doe <ex@mp.le>`_)_
Would be particularly nice for when those emails are tracked, since the notifications would display the name instead of just the email.

(https://cloud.githubusercontent.com/assets/4140885/16849075/6580ba92-49be-11e6-9695-11fbb1603257.png)

**Comment by bengotow** [comment]
This would definitely be a nice feature. Thanks!
