### ISSUE TITLE
No more than one item shows up in "Starred"

### ISSUE THREAD

**Issue by amybruno** [nylas/nylas-mail#2637]
Title says it all: I have multiple items starred but only 1 shows up at a time when I click on the "Starred" folder. 

Adding and removing stars has no effect. In particular, removing a star when I am in the "Starred" folder removes the item from the list and makes it look like there are no starred item. If I indeed have other things starred, then clicking away to some other folder and coming back to the "Starred" folder will show one of the other starred items, but only one of them.

**Comment by jackiehluo** [comment]
Hmmm, interesting. Which mail provider are you using?

**Comment by chr-br** [comment]
This is with an institutional exchange account. It's the only account I'm using with Nylas.

**Comment by jengendler** [comment]
I'm having the same problem. I have two gmail accounts and one account with a hosting company. When I go to the collective Starred folder (for all accounts), only the first starred email shows up. When I click on an individual account under Starred, I see all of that account's starred emails. Strange behavior. At least I can access my starred emails, I just don't use the collective Starred folder.

**Comment by jackiehluo** [comment]
Another incidence: https://nylas.zendesk.com/agent/tickets/5795

**Comment by OJFord** [comment]
I'm also seeing this with Gmail.

8 starred emails (or threads, I suppose?) in Inbox; 1 in Starred.

Even more curiously, the one in Starred was *not* in Inbox (even though it was not archived) until I added it manually. But now that I have, it remains in Starred; the others still not.

**Comment by OJFord** [comment]
It's also worth noting that if you un-star the one item there it doesn't seem to apply, but if you click away (to say, Inbox) and then back into Starred it will have been replaced by a new, single, starred item.

**Comment by OJFord** [comment]
Well, [it's not `limit(1)`](https://github.com/nylas/N1/blob/29e453681a723de2e2ad2cde59f16e345dcb1199/src/mailbox-perspective.coffee#L191-L194)...
```coffeescript
 query = DatabaseStore.findAll(Thread).where([
  Thread.attributes.starred.equal(true),
  Thread.attributes.inAllMail.equal(true),
]).limit(0)
```

Presumably `limit(0)` is unlimited? I'm not familiar with Nylas' query-builder/database setup, and I can't get it to build at the moment or I'd try removing it just to see.
