### ISSUE TITLE
Failed to load 'config.json' -- Unexpected token.

### ISSUE THREAD

**Issue by juanscv** [nylas/nylas-mail#2800]
After reboot, Nylas won't open, it gives the error 
Failed to load config.json
Unexpected token

Upon inspecting the config.json file, it is entirely blank, just a bunch of spaces.

Had to reset configuration.

This is the second time it's happened.

---

Windows 10 Pro
Nylas v. 0.4.5

*Bug

Installed plugins: 
Wunderlist
User Avatars
Unsubscribe
Events Calendar
Mail in chat

**Comment by jackiehluo** [comment]
@juanscv Just to confirm—are you on 0.4.51?

**Comment by emorikawa** [comment]
Another incidence: https://nylas.zendesk.com/agent/tickets/6342

**Comment by juanscv** [comment]
@jackiehluo Yes.

**Comment by julietaolivero** [comment]
I have already reseted configurations 5 times. I dont bother to configure all my accounts anymore. Configuring all accounts and signatures every time it fails is really frustrating!  Did you find a solution for this?

**Comment by jtflynnz** [comment]
This was also occurring in this issue: #2518; Referencing here to tie the two issues together.

**Comment by jstejada** [comment]
merging into #3382
