### ISSUE TITLE
Copyright symbol ©

### ISSUE THREAD

**Issue by luangjokaj** [nylas/nylas-mail#3113]
##### Are there any related issues?

No related issues.

##### What operating system are you using?
MacOS Sierra 10.12.1

##### What version of N1 are you using?
Version 0.4.400 (0.4.400)

--

**Bug?**

The copyright symbol always get replaced with an image. Instead of being a normal symbol part of the typography. It looks awful. 
[
<img width="787" alt="screen shot 2016-12-02 at 20 26 46" src="https://cloud.githubusercontent.com/assets/6809696/20847449/6738ea42-b8ce-11e6-9f4d-6a6c71ca6b8c.png">
](url)

##### Do you have any third-party plugins installed? If so, which ones?
No plugins.

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No

##### Is the issue reproducible with a particular attachment, message, signature, etc?

No. You can see this problem on all mails that have the copyright © symbol.

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
/

**Comment by bengotow** [comment]
Wow that's so random! Good find. I think we might be replacing it with the copyright emoji (is there one?)

**Comment by luangjokaj** [comment]
@bengotow yep there is -> ©️

**Comment by noilly** [comment]
The same goes for the trademark symbol.
