### ISSUE TITLE
Add option to "Process entire mailbox", applying mail rules to archive

### ISSUE THREAD

**Issue by OJFord** [nylas/nylas-mail#3159]
macOS 10.12.2; N1 0.4.402

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No

--

'Process entire mailbox' does not work in 'Mail Rules'.

It first appears with some small number, always the same, and then disappears - as if maybe it had finished (but far too quickly).

I cannot find any to which they've been applied though, other than new incoming emails.

**Comment by OJFord** [comment]
Correction: this is a feature request.

(Solution to bug is faulty expectation... I expected "entire mailbox" to mean that; not inbox only.)

Suggestion:
- Rename 'process entire mailbox' option to 'process inbox'.
- Add option 'process inbox & archive'

**Comment by emorikawa** [comment]
Related to https://github.com/nylas/N1/issues/1074 and https://github.com/nylas/N1/issues/2486

**Comment by OJFord** [comment]
Oh, whoops, I guess it's a duplicate of #2486.
