### ISSUE TITLE
Store mail rules in config.json

### ISSUE THREAD

**Issue by OJFord** [nylas/nylas-mail#3161]
macOS 10.12.2; N1 0.4.402

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
Not sure.

--

I store Nylas and other configurations in VCS so that I can keep multiple systems synchronised, not worry about losing the disk or reformatting (and having to re-specify all my settings), etc.

To that end, I'd really like it if N1's mail rules could be stored in the config.json file (or a rules.json, like the existing keymap.json), which they presently seem not to be; nor in any other human-readable file in that directory.

**Comment by emorikawa** [comment]
We have plans to keep mail rules on the Nylas ID so they transfer properly between different installations on different computers

**Comment by OJFord** [comment]
> We have plans to keep mail rules on the Nylas ID

Is that why they're not in Basic? Or does Basic still require a Nylas ID?

(Also, personally I'd really prefer a config file, even if also tied to ID.)
