### ISSUE TITLE
Nylas Pro: Trash not working

### ISSUE THREAD

**Issue by OJFord** [nylas/nylas-mail#3189]
macOS 10.12.2; Nylas 1.5.0

**Bug**
##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Only using Gmail, so 🤷‍♂️ 

##### Is the issue reproducible with a particular attachment, message, signature, etc?
N/A

--

If I select an item, or multiple items, and then press my 'Trash' shortcut, I'd expect them to go. When I do that, however, it pops up saying 'Applying labels' - then nothing (no labels change).

Still in inbox; still in Gmail web UI. 

NB I'm trying this on emails in Spam, since they're the only ones I delete. (Everything else just gets archived.)

**Comment by OJFord** [comment]
Further to this, spam doesn't seem to synchronise with Gmail - so if I delete them in the web UI, they still show unread and in spam in Nylas.

**Comment by OJFord** [comment]
@jstejada This is an issue in both Pro and Basic versions.

**Comment by jstejada** [comment]
thanks! merging this ino #3261
