### ISSUE TITLE
Selecting emails with hotkey does not refresh inbox list view

### ISSUE THREAD

**Issue by elliottkember** [nylas/nylas-mail#3191]
Selecting an email using hotkeys does not update the display. If I press "x" to select an email, the email does not appear selected although the action bar drops in.

**Comment by elliottkember** [comment]
![selection](https://cloud.githubusercontent.com/assets/42827/22078704/f4573e42-dd86-11e6-8e2d-61693d769a4e.gif)

It's hard to spot in this gif, because changing selection with a hotkey *does* update the list. When the first email is selected, it does not show as selected.

**Comment by spang** [comment]
Thanks for this report @elliottkember! We can reproduce the issue and we're taking a look into fixing it. :)

**Comment by jstejada** [comment]
this should be fixed in the latest version!
