### ISSUE TITLE
The new 'Nylas Mail' app is unable to sync and results in leaving the computer frozen

### ISSUE THREAD

**Issue by avanish0509** [nylas/nylas-mail#3198]
Hi, 

I was running Nylas N1 fine with the sync-engine running on my machine but since yesterday when I switched to the free Nylas Mail app, my Gmail and Outlook.com are giving a false error that "Nylas Mail is offline" whereas the mails do sync. Although, it's resulting in leaving my computer (OS X El Capitan Version 10.11.6) frozen such that the mouse and keyboard are left useless. Below is a screenshot of Nylas Mail app on my machine:

![nylas mail syncing issue](https://cloud.githubusercontent.com/assets/9089367/22121129/ac49d37e-de50-11e6-95bc-af02dcc71350.jpg)

I re-installed the app but it didn't make any difference

**Comment by jstejada** [comment]
Hi @avanish0509 thanks for reporting this! We're releasing a new version today that should fix an issue that made the app freeze (3e85aa4).

If you can, can you open the activity window with `cmd+alt+w` and then dev tools with `cmd+alt+i`, select the Console and send me a screenshot of any errors you see there? You can also send it to support@nylas.com

Thanks for your patience!

**Comment by jstejada** [comment]
Hi @avanish0509 just released 1.0.11, let me know if you are still having issues! Thanks

**Comment by ravasthi** [comment]
@jstejada I'm seeing a similar problem. I'm running 1.0.11

* My iCloud account reports syncing errors nearly constantly, 
* the client is always syncing, 
* the client is pegging at least two cores—CPU utilization of ~250%,
* and after a reboot this morning, doesn't load up at all (screenshot attached). I tried to toggle the developer tools but nothing happened.

![unresponsive-nylas](https://cloud.githubusercontent.com/assets/83881/22184593/a2ef4918-e089-11e6-9f4e-61ab6951e8fe.png)

**Comment by avanish0509** [comment]
Hi @jstejada I'm still seeing the same issue although unlike @ravasthi my screen doesn't freeze any longer but I still continue to have the connectivity issues. Below is the error message, followed by it's screenshot:

`Error
    at new APIError (/src/flux/errors.es6:28:19)
    at _priorityUiCoordinator2.default.settle.then (/src/flux/nylas-api-request.es6:177:30)
    at tryCatcher (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromiseCtx (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/promise.js:604:10)
    at Async._drainQueue (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/async.js:138:12)
    at Async._drainQueues (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/async.js:17:14)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)`

![nylas- error console screenshot](https://cloud.githubusercontent.com/assets/9089367/22214718/bdd37e88-e166-11e6-8b9f-0ed8a711bbe5.jpg)

**Comment by ravasthi** [comment]
I was able to get the app to restart running with debug flags after force quitting it, but didn't get anything too useful. Including the screenshot in case it is:

![unresponsive-nylas-02](https://cloud.githubusercontent.com/assets/83881/22216937/e60f4500-e155-11e6-92b7-6212c4972be5.png)

**Comment by jweinstein** [comment]
Same issues here

**Comment by jstejada** [comment]
possibly related to #3178

**Comment by jstejada** [comment]
we've released v 1.0.15 today-- are folks still seeing this issue?

**Comment by avanish0509** [comment]
The latest update 1.0.15 fixed the syncing issue. Now both my gmail and outlook.com sync fine and the cpu usage is low as well. But as soon as the Nylas window looses focus i.e. when I switch to another app, it shows the "Nylas is offline" message. Below is a screenshot. **Although it is to be noted that even with this error shown, the email do come in.** 
![image](https://cloud.githubusercontent.com/assets/9089367/22348605/5ca901fc-e3da-11e6-8e5c-6d9d1112cabf.png)

**Comment by ravasthi** [comment]
I won't have a chance to check the machine on which the app is completely unresponsive until later, but on one of the machines it still runs on on, I still see the sync error message. The error message with stack trace is:

Sync Error:
```
{
  "message": "Mailbox does not exist",
  "source": "protocol",
  "stack": "Error: Mailbox does not exist\\n    at Connection._resTagged (/Applications/Nylas Mail.app/Contents/Resources/app.asar/internal_packages/local-sync/node_modules/isomorphic-core/node_modules/imap/lib/Connection.js:1497:11)\\n    at Parser.<anonymous> (/Applications/Nylas Mail.app/Contents/Resources/app.asar/internal_packages/local-sync/node_modules/isomorphic-core/node_modules/imap/lib/Connection.js:193:10)\\n    at emitOne (events.js:96:13)\\n    at Parser.emit (events.js:188:7)\\n    at Parser._resTagged (/Applications/Nylas Mail.app/Contents/Resources/app.asar/internal_packages/local-sync/node_modules/isomorphic-core/node_modules/imap/lib/Parser.js:175:10)\\n    at Parser._parse (/Applications/Nylas Mail.app/Contents/Resources/app.asar/internal_packages/local-sync/node_modules/isomorphic-core/node_modules/imap/lib/Parser.js:139:16)\\n    at Parser._tryread (/Applications/Nylas Mail.app/Contents/Resources/app.asar/internal_packages/local-sync/node_modules/isomorphic-core/node_modules/imap/lib/Parser.js:82:15)\\n    at TLSSocket.Parser._cbReadable (/Applications/Nylas Mail.app/Contents/Resources/app.asar/internal_packages/local-sync/node_modules/isomorphic-core/node_modules/imap/lib/Parser.js:53:12)\\n    at emitNone (events.js:86:13)\\n    at TLSSocket.emit (events.js:185:7)\\n    at emitReadable_ (_stream_readable.js:432:10)\\n    at emitReadable (_stream_readable.js:426:7)\\n    at readableAddChunk (_stream_readable.js:187:13)\\n    at TLSWrap.onread (net.js:543:20)\\n    at Socket.ondata (_stream_wrap.js:58:20)\\n    at emitOne (events.js:96:13)\\n    at Socket.emit (events.js:188:7)\\n    at readableAddChunk (_stream_readable.js:176:18)\\n    at TCP.onread (net.js:543:20)",
  "textCode": "NONEXISTENT",
  "type": "no"
}
```

Obviously the mailbox does exist, because it does sync, even though it reports syncing errors.

Also, if it's useful to know, I think that the iCloud account is the last one in the account list on each of the three machines I've got Nylas Mail installed on, each of which, when the app loads, have this syncing issue.

**Comment by jstejada** [comment]
great, thanks for the details! @ravasthi , so this error is being thrown exclusively for your iCloud account?

**Comment by ravasthi** [comment]
@jstejada Yes, exclusively for that account. I'll report back about the unresponsive client later tonight.

**Comment by ravasthi** [comment]
@jstejada Happy to report that the totally unresponsive client is now loading, and the only remaining issue is the syncing error described above.

**Comment by jstejada** [comment]
thanks! I'm going to close this issue for now. Feel free to open another issue for icloud syncing issues (we are working on it anyway)
