### ISSUE TITLE
Release notes link in the update prompt in Nylas Mail links to Nylas N1 changelog

### ISSUE THREAD

**Issue by sebastian** [nylas/nylas-mail#3200]
When prompted to update Nylas Mail in the app itself, there is a "View changelog" link presented. It links to the [N1 Changelog](https://github.com/nylas/N1/blob/master/CHANGELOG.md) rather than the [Release](https://github.com/nylas/N1/releases/tag/1.0.10) page. The former contains no useful information about the update.

Thanks!

**Comment by jstejada** [comment]
thanks @sebastian , this should be fixed in the next release

**Comment by jstejada** [comment]
this should be fixed on 1.0.26 which was released today! Thanks for your patience!
