### ISSUE TITLE
Stuck on sync

### ISSUE THREAD

**Issue by jweinstein** [nylas/nylas-mail#3235]
After ~7 hour of syncing a large Gmail account, no new progress.

![image](https://cloud.githubusercontent.com/assets/547354/22392039/3a9971a2-e4aa-11e6-95aa-3334b0f86510.png)

**Comment by jweinstein** [comment]
CPU still churning. ![image](https://cloud.githubusercontent.com/assets/547354/22392086/9b81175e-e4aa-11e6-9494-dd53e839c457.png)

**Comment by jweinstein** [comment]
Had received a `Sync` error, clicked `Try again`

**Comment by jweinstein** [comment]
Should I let it sit here, worth reviewing logs, or should I restart the app?

**Comment by jstejada** [comment]
@jweinstein gonna merge into #3232 
can you post the errors you were having?

**Comment by SeerUK** [comment]
It'd be useful to have maybe a progress bar of some description. I'm having a similar issue, but I think it's just taking a long time. If it said the current progress (percent or number of messages?) then it would at least let people know something is happening. My CPU is going, and the icons are flashing... but I still don't know if anything is happening right now. I've got to do this with a few accounts too!
