### ISSUE TITLE
n1-unsubscribe plugin -- Nylas Mail Helper quit unexpectedly.

### ISSUE THREAD

**Issue by pamo** [nylas/nylas-mail#3243]
##### Are there any related issues?
Don't seem to be finding any similar issues.

##### What operating system are you using?
macOS Sierra 10.12.3 (16D32)

##### What version of Nylas Mail are you using?
Version 1.0.17 (1.0.17)
--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
* Unsubscribe
* Participants List

But still happens after disabling them and uninstalling them.

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
I only have Gmail enabled.

##### Is the issue reproducible with a particular attachment, message, signature, etc?
Happens on load. Inbox doesn't load messages list.

Console shows the following

```
/Applications/Nylas Mail.app/Contents/Resources/app.asar/src/nylas-env.js:316 TypeError: _nylasExports.NylasAPI.makeRequest is not a function
    at ThreadUnsubscribeStore._loadMessagesViaAPI (thread-unsubscribe-store.es6:98:18)
    at ThreadUnsubscribeStore._loadLinks (thread-unsubscribe-store.es6:65:10)
    at new ThreadUnsubscribeStore (thread-unsubscribe-store.es6:35:12)
    at ThreadUnsubscribeStoreManager.getStoreForThread (thread-unsubscribe-store-manager.es6:11:26)
    at ThreadUnsubscribeQuickActionButton.load (unsubscribe-buttons.jsx:89:50)
    at ThreadUnsubscribeQuickActionButton.componentWillMount (unsubscribe-buttons.jsx:22:10)
    at measureLifeCyclePerf (/Applications/Nylas 
```

**Comment by jstejada** [comment]
hi @pamo , thanks for the report! this seems to be an error that's coming from within the https://github.com/colinking/n1-unsubscribe plugin. Maybe you should open the issue in that repo?

@colinking we changed api's quite a bit for the Nylas Mail release, which I think is breaking the `thread-unsubscribe-store`-- sorry about that.

 You should be able to use `new NylasAPIRequest.run()`. You can ping me on the Nylas Community Slack Channel if you have any questions

**Comment by KyleKing** [comment]
Thanks, @jstejada, we were only missing the `NylasAPI.makeRequest()` => `new NylasAPIRequest.run()` update! The new release is available here: https://github.com/colinking/n1-unsubscribe/releases/tag/2.0.1

**Comment by pamo** [comment]
Just installed the latest version @KyleKing @jstejada. No more issues! 🥇

**Comment by jstejada** [comment]
glad to hear it!
