### ISSUE TITLE
Submodule K2 clone failure

### ISSUE THREAD

**Issue by garth-wells** [nylas/nylas-mail#3244]
Cloning nylas-mail using
```
git clone --recursive https://github.com/nylas/nylas-mail.git
```
leads to the error:
```
Submodule 'src/K2' (git@github.com:nylas/K2.git) registered for path 'src/K2'
Cloning into 'src/K2'...
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:nylas/K2.git' into submodule path 'src/K2' failed
```

This same problem causes an error when running bootstrap:
```
./script/bootstrap 

{ Error: Command failed: git submodule update --init --recursive
Cloning into 'src/K2'...
ERROR: Repository not found.
fatal: Could not read from remote repository.
```

**Comment by ConorIA** [comment]
Nylas K2 is 404 at https://github.com/nylas/K2!

**Comment by grinich** [comment]
sorry this is a private repo not yet open sourced. for now you should build from the `n1-pro` branch

**Comment by ConorIA** [comment]
@grinich, any remedy for someone whose pro trial has expired? My accounts have all been paused.

**Comment by grinich** [comment]
pay us? or you can download the limited Mac-only version from our website

**Comment by grinich** [comment]
(going to close this because it's not technically a bug)

**Comment by ConorIA** [comment]
> pay us? 

Ha! I should have seen that one coming. Sorry, I had meant whether there was any sort of stop-gap until the Linux Nylas Mail client is ready. Didn't mean to come across as a freeloader (though I guess admit, in this case that's exactly what I am). I'll just wait patiently until either K2 is opened, or until the Linux builds are posted.

**Comment by garth-wells** [comment]
@grinich The blog at https://blog.nylas.com/nylas-mail-is-now-free-8350d6a1044d#.p6xox8o70 is misleading and disingenuous. Here's an extract: 

> Is Nylas Mail open source?
> Yep! You can find the code on GitHub, and it’s still GPL.
 
Maybe the front-end client is, but it's largely useless without an open backend (K2).

**Comment by grinich** [comment]
Sorry it's unclear-- that repo will get open sourced when we ship the Linux builds so you can either download the binary from our side our build from scratch.

We are really short staffed right now. If you know anyone looking for a job, send them our way! jobs.lever.co/nylas

**Comment by pangorgo** [comment]
is K2 appearance in changelog means K2 is going public soon, and build on linux will be possible again?

**Comment by anidotnet** [comment]
#3270

**Comment by jankun** [comment]
think it would be good to clarify this- since you are kind of violating GPL

**Comment by themancalledjakob** [comment]
so basically it is impossible at the moment to build a functioning nylas-mail client with self hosted sync-engine yourself on linux?

**Comment by ArchangeGabriel** [comment]
@themancalledjakob Doesn’t N1 still works in this context?

**Comment by themancalledjakob** [comment]
@ArchangeGabriel github.com/nylas/N1 forwards me to github.com/nylas/nylas-mail.
There the n1-pro branch mentioned above gives me a similar 404/permission error for the "edgehill" submodule.

Am I missing something obvious?

**Comment by ArchangeGabriel** [comment]
@themancalledjakob Hum, I thought N1 was buildable on Linux (here in Arch for instance: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=n1-git), but maybe that’s no longer the case. Dunno about this “edgehill” submodule, but it indeed looks to be to N1 what K2 is to Nylas Mail… Regarding the sync-engine, I think it can still be built [from source](https://github.com/nylas/sync-engine), but not sure whether you can specify a self-hosted sync-engine within N1, or if it must be done at compile time, in which case you’re screwed.

Anyhow, I hope that the everything will be buildable from source and not mandatorily rely on a cloud part soon enough.

**Comment by themancalledjakob** [comment]
@ArchangeGabriel Exaclty, it _was_ buildable on Linux from the former N1 repository. From nylas-mail I couldn't figure anything out yet that doesn't require access to private repositories.

And yes, sync-engine is buildable on Linux. Which I did and configured everything and am therefore a bit frustrated to have done for nothing.

Considering the option to use the binary: Even if the self hosted sync-engine could be selected, the in the [readme](https://github.com/nylas/nylas-mail) mentioned download links for binary .deb packages are gone.

Weirdly also the in their blog mentioned [exciting roadmap for the bright open source future of Nylas](https://trello.com/b/hxsqB6vx/n1-open-source-roadmap) is private. If they don't want to share it, why proudly pointing to it in an open blog?

I assume that this situation is temporary as @grinich said. But then they should mention that clearly, so motivated people don't waste their time. A temporary disclaimer would be nice.

Anyway, I hope this gets available somehow for Linux soon again.

**Comment by ArchangeGabriel** [comment]
The README is for Nylas Mail, which doesn’t have any Linux binary at the time. But README from n1-pro is outdated anyway, however binaries are [here](https://billing.nylas.com/download-pro) and [here](https://github.com/nylas/nylas-mail/releases/tag/1.5.0).

I wasn’t knowing about that Trello board, that’s strange indeed.

**Comment by kuboosoft** [comment]
https://github.com/UnitedRPMs/nylas-mail

**Comment by jtflynnz** [comment]
> Weirdly also the in their blog mentioned exciting roadmap for the bright open source future of Nylas is private. If they don't want to share it, why proudly pointing to it in an open blog?

>  I wasn’t knowing about that Trello board, that’s strange indeed.


Another caveat to the Trello board; it was previously public (since the days of N1 being an invite beta), so it was actively changed to make it private. In the meantime, the public Github-equivalent has not been set up.

**Comment by grinich** [comment]
We switched to voting on features on GitHub. The Trello board was from a time before GitHub issues had reactions. We've moved all of the relevant cards to GitHub now.

**Comment by captn3m0** [comment]
>Sorry it's unclear-- that repo will get open sourced when we ship the Linux builds so you can either download the binary from our side our build from scratch.

Can we expect K2 repo to be open sourced anytime soon?

**Comment by grinich** [comment]
@captn3m0 it's now merged into mainline and not a separate repo. Just clone master and you should be able to build fully from source
