### ISSUE TITLE
Changelog link results in a 404 with Update Notification

### ISSUE THREAD

**Issue by pamo** [nylas/nylas-mail#3246]
##### What operating system are you using?
macOS 10.12.3 (16D32)

##### What version of Nylas Mail are you using?
1.0.17

**Bug?**
##### Is the issue reproducible with a particular attachment, message, signature, etc?
When I click on the changelog link in the update notification, I am directed to this url, which results in a 404.
https://github.com/nylas/nylas-mail/blob/n1-next/CHANGELOG.md

![image](https://cloud.githubusercontent.com/assets/784889/22482654/c0446eae-e7ae-11e6-9ca8-3b6500a158b9.png)

**Comment by jstejada** [comment]
thanks! this should be fixed in the next release

**Comment by jstejada** [comment]
this should be fixed on 1.0.26 which was released today! Thanks for your patience!
