### ISSUE TITLE
Update installs as N1, erasing prefs

### ISSUE THREAD

**Issue by kbohinski** [nylas/nylas-mail#3248]
##### Are there any related issues?

Don't think so...

##### What operating system are you using?
OSX

##### What version of Nylas Mail are you using?
Update pushed today

**Comment by jadengore** [comment]
This is an issue for me still, can you reopen @kbohinski?

**Comment by kbohinski** [comment]
Sure!

I fixed this by clearing the ~/.nylas folder and reinstalling... Hope that helps...

**Comment by jstejada** [comment]
Is this an issue in 1.0.32?

**Comment by jadengore** [comment]
@jstejada Yes

**Comment by hallamoore** [comment]
This should be fixed now! Let us know if the issue persists.

**Comment by jadengore** [comment]
@hallamoore do i need to delete my .nylas folder as @kbohinski said? Will it remove saved configs like signature, etc?
