### ISSUE TITLE
Custom IMAP Account : IMAP and SMTP throwing feilds throwing error when address has extra space

### ISSUE THREAD

**Issue by hfactor** [nylas/nylas-mail#3250]
While creating a custom IMAP Account, Nylas is throwing errors when there is an extra space in end of the line. (--.com ) instead of (--.com)
Also, the error is too complex to understand. Attaching screenshot.
<img width="668" alt="screen shot 2017-02-01 at 6 36 26 pm" src="https://cloud.githubusercontent.com/assets/1788677/22507891/99929ce0-e8ad-11e6-98e0-986ca2353992.png">

**Comment by jstejada** [comment]
thanks for the report! this should be fixed in the next release

**Comment by jstejada** [comment]
this should be fixed on 1.0.26 which was released today! Thanks for your patience!
