### ISSUE TITLE
When doing an initial IMAP sync, Nylas opens an increasing number of connections but never gets past "Gathering folders"

### ISSUE THREAD

**Issue by nvahalik** [nylas/nylas-mail#3267]
Every time I have removed and re-added my IMAP account, it says "gathering folders" in the sync window but it never actually does anything. I'm using Dovecot hosted on a cPanel 12.x server. I can see the connections being made from my machine to the server. Over time the total number of open connections continues to rise until finally the maximum number of connections allowed user user/ip combination is reached... at which point Nylas says that it can no longer reconnect.

My IMAP Path Prefix is "INBOX".

##### Are there any related issues?
None that I'm aware of.

##### What operating system are you using?
OSX 10.11.6 (15G1217)

##### What version of N1 are you using?
1.0.15

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
IMAP

##### Is the issue reproducible with a particular attachment, message, signature, etc?
Yes, this happens every time I go through the addition of my IMAP account.

This is what happens when I occasionally check the `netstat` output on the server:
![root_vps___ _ssh_vps_ _108x125](https://cloud.githubusercontent.com/assets/632120/22353637/0b50bb80-e3e7-11e6-8907-eb68b165f681.jpg)

**Comment by nvahalik** [comment]
Sorry, this is essentially a duplicate of #3228. My apologies if this is incorrect procedure. However, the previous updates did not fix the issue.

**Comment by jstejada** [comment]
hi @nvahalik , thanks for the thorough information. I'm going to merge it into #3228
