### ISSUE TITLE
Cannot click on "Terms of Service" or "Privacy Policy" links on "Create a Nylas ID" page

### ISSUE THREAD

**Issue by noelmarkham** [nylas/nylas-mail#3271]
##### Are there any related issues?

None found
...

##### What operating system are you using?
OSX
...

##### What version of Nylas Mail are you using?
1.0.21
...

--

Clicking on the "Terms of Service" and "Privacy Policy" links on the "Create a Nylas ID" page do nothing. Consequently I don't know what I'm signing up for, and so cannot sign up.

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
...

##### Is the issue reproducible with a particular attachment, message, signature, etc?

...

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
...

**Comment by dtsitses** [comment]
same problem here

**Comment by noelmarkham** [comment]
Cleaning up my open issues. Haven't checked if this was ever fixed as I'm using other clients.
