### ISSUE TITLE
Nylas is blurry on my retina screen.

### ISSUE THREAD

**Issue by samjau** [nylas/nylas-mail#3278]
Running macOs sierra 10.12.3 w/ Nylas N1 version 1.0.21.

Honestly not sure how to repro this, but nylas was displaying fine until today when it randomly switched into non-retina mode & now everything is blurry.

I restarted my machine, re-installed nylas, reset all settings and still no dice.

**Comment by light2yellow** [comment]
@samjau post the output of
```zsh
cat /Applications/Nylas\ N1.app/Contents/Info.plist | grep -A1 NSHighResolutionCapable
```
If this fails (and it probably will, because the above is for legit N1 (which is 1.5)), try this (not tested):
```zsh
cat /Applications/Nylas\ Mail.app/Contents/Info.plist | grep -A1 NSHighResolutionCapable
```

**Comment by samjau** [comment]
Here's what i get: 
    <key>NSHighResolutionCapable</key>
    <true/>

**Comment by light2yellow** [comment]
@samjau you need to paste the output *exactly* how it appears. For example:
```xml
% cat /Applications/Nylas\ N1.app/Contents/Info.plist | grep -A1 NSHighResolutionCapable
    <key>NSHighResolutionCapable</key>
    <true/>
```

**Comment by samjau** [comment]
```
cat /Applications/Nylas\ Mail.app/Contents/Info.plist | grep -A1 NSHighResolutionCapable
    <key>NSHighResolutionCapable</key>
    <true/>
```

**Comment by light2yellow** [comment]
@samjau yep, that was expected. This key is responsible for high resolution. I guess something is broken inside your workspace and not within Nylas. Did you spot any other app(s) going blurry like this? Also if you don't mind redownloading all the mail you can delete it with the application settings via `rm -rf ~/.nylas*`.

**Comment by samjau** [comment]
@light2yellow nope, all other apps are fine. I removed all application settings and pref files. Unfortunately nylas is still blurry.

**Comment by light2yellow** [comment]
@samjau sorry, not much I can do from this point. It's still possible that Nylas broke something in their APIs though (and because they're using Electron it might be an upstream issue).

**Comment by samjau** [comment]
@light2yellow Super embarrassing, but I apparently I had accidentally "Open in low resolution" in the app info pane selected: 
https://www.dropbox.com/s/vgy8ehm14t237f9/Screenshot%202017-02-15%2011.58.47.png?dl=0

Sorry about putting you through this, thanks for all your help!
