### ISSUE TITLE
Selected threads - only 2 highlighted

### ISSUE THREAD

**Issue by augustoms** [nylas/nylas-mail#3280]
Hi guys,

I noticed that when using the 2 panel layout, when selecting multiple threads, only the first 2 selections are highlighted.

The right-panel (that originally shows the message content) shows the correct number of selected conversations, but as said, only 2 itens in the messages list stay highlighted.

 But It turns highlighted if you change the threads list width.

I'm using:

- OSX 10.11.6
- Nylas Version 1.0.21 (1.0.21)
- Tested with all default themes.
- Appearance layout: 2 panel

There are two different ways to reproduce:

**1) Selecting messages one by one**

- set the appearance layout to TWO PANEL;
- access any folder in any account (all mail, inbox, sent...)
- select one threads (it will highlight), then, with cmd key pressed, select any other threads (it will highlight too). Still with cmd key pressed, and select other threads (it will not highlight, but the right panel will count this threads in the total)
![image](https://cloud.githubusercontent.com/assets/3129481/22842486/8818dd06-efbc-11e6-9509-55f0c9a1908f.png)

- If you change the threads list width (the sufficient to change its appearance - image 1), the unhighlighted messages will be highlighted (image 2)
Image 1:
![image](https://cloud.githubusercontent.com/assets/3129481/22842548/b0e60d30-efbc-11e6-9de4-8e7dabed7e12.png)
Image 2:
![image](https://cloud.githubusercontent.com/assets/3129481/22842555/bb0fde1c-efbc-11e6-9e8b-ea5cee1e04d3.png)

**2) Selecting messages whit shift key**
- set the appearance layout to TWO PANEL;
- access any folder in any account (all mail, inbox, sent...)
- select one threads (it will highlight), then, with shift key pressed, select any number of threads below (or above) the initial selection (it will highlight too, doesn't matter if you select a group of 2 or 15 threads). Still with shift key pressed (or you can change it, pressing the cmd key), and select other threads (it will not highlight, but the right panel will count this threads in the total)
![image](https://cloud.githubusercontent.com/assets/3129481/22842733/817e99bc-efbd-11e6-964d-b96cd0af7bf4.png)

- If you change the threads list width (the sufficient to change its appearance), the unhighlighted messages will be highlighted

**Comment by jstejada** [comment]
this should be fixed on 1.0.26 which was released today! Thanks for your patience!
