### ISSUE TITLE
Custom IMAP Account Creation Locked in "Syncing your mailbox..."

### ISSUE THREAD

**Issue by edarioq** [nylas/nylas-mail#3281]
Title says it all, haven't been able to use Nylas because of this. I've uninstalled and installed Nylas several times, restarted, even restarted my machine (macOS Sierra 10.12.3). It just stays like this :(

![screenshot 2017-02-11 15 41 26](https://cloud.githubusercontent.com/assets/1882457/22857290/9c0725f2-f070-11e6-8cca-8229ebc64781.png)

**Comment by edarioq** [comment]
Just saw a moderator comment about a patch incoming, will this address the issue I am reporting?

https://github.com/nylas/nylas-mail/issues/3232

**Comment by jstejada** [comment]
Yep, merging ino #3232
