### ISSUE TITLE
Cannot send mails [Syncback Task Failed] : Sending Failed

### ISSUE THREAD

**Issue by abhishekbanthia** [nylas/nylas-mail#3283]
##### Are there any related issues?

...

##### What operating system are you using?
...
macOS Sierra 10.12.1

##### What version of Nylas Mail are you using?
...

1.0.21
--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
...
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
... 

I've a single iCloud acount

##### Is the issue reproducible with a particular attachment, message, signature, etc?

...

--

Issue reproducible with/without attachments.

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
...

<img width="532" alt="screen shot 2017-02-13 at 9 43 38 am" src="https://cloud.githubusercontent.com/assets/8280282/22887696/051b3810-f1d1-11e6-9540-78d311f17188.png">

**Comment by jstejada** [comment]
thanks for the report! merging into #3182
