### ISSUE TITLE
Unknown \Muted & \Trash labels

### ISSUE THREAD

**Issue by axllent** [nylas/nylas-mail#329]
I have two labels named `\Muted` and `\Trash` appearing in my Labels which aren't labels I created, nor labels that are accessible/visible via IMAP or Gmail web interface.

Both folders (probably Gmail-specific) are empty, even though I have `[Google Mail]/Bin` which does have messages, so it seems `\Trash` and `[Google Mail]/Bin` aren't related.

**Comment by bingocaller** [comment]
Did you use something like Airmail before? I muted a few conversations in there and they show up under `\Muted` in N1.

**Comment by axllent** [comment]
No I haven't sorry, the only conversations I have ever muted in the past were directly via the gmail web interface (I wasn't even aware that other programs supported muting).

But there are no messages in there now (all unmuted), and the other label is also empty (though I do have stuff in my trash).

**Comment by mcescalante** [comment]
I am also seeing an empty \Trash label in Nylas that is not in my Labels in Gmail:

![https://i.imgur.com/mbBJyii.png](https://i.imgur.com/mbBJyii.png)

**Comment by amrro** [comment]
I have two labels \All & \trash plus deleted labels from gmail.

![labels_problem](https://cloud.githubusercontent.com/assets/12991700/11019931/6d7cf514-8617-11e5-9ffc-d66170435313.png)

**Comment by alexandru-calinoiu** [comment]
I have them also, on top of this existing labels don't get removed even when I remove them from gmail.

**Comment by bengotow** [comment]
Hey folks—thanks for reporting these label issues. It's possible for folders to be exposed via Gmail's IMAP API that aren't visible when you use the Gmail web interface. We'll dig in and see if we can figure out where these are coming from and handle them better in the app.

**Comment by deadlyhifi** [comment]
I had the same labels but just right clicked and deleted them without issue. I did have Airmail and perhaps some other email clients installed in the past.

**Comment by axllent** [comment]
It seems the latest N1 version now has this feature (to right-click and "delete" a label). That's good news, although maybe they should not use the word "delete" as it appears that it doesn't actually delete it (at least not in the upstream mailbox), but seems to rather *hide* it within N1 itself. If I "delete" a label in N1 the actual label remains in my Gmail (web).

On that note, maybe now an "unhide" may be necessary for accidental "deletions"? Oh well, a good step in the right direction either way :)

**Comment by joelabair** [comment]
I noticed the \Trash label appearing as well.  I think i had unchecked the "unread count" option, which seemed to trigger the appearance of 
Trash.  

After I right-click deleted \Trash, I can not reproduce, however.

**Comment by dansutera** [comment]
Also can't delete my \Trash folder

**Comment by jakedeg** [comment]
I have \Muted on a Google Apps account. But no \Trash. 
The messages in \Muted do appear to be ones that I muted using the google web interface. 

If https://github.com/nylas/N1/issues/764 gets integrated, presumably it would make smarter use of this \Muted label.

**Comment by huylv** [comment]
I have `\All` label appeared today. No idea where it came from. The only way I can think of to remove/resync all the labels is to delete `~/.nylas` directory and add all accounts again. But that's painful since I have 5 accounts.

**Comment by syabro** [comment]
![](http://s.syabro.com/9xwfu.png)
