### ISSUE TITLE
How to use the Task class in a plugin

### ISSUE THREAD

**Issue by miguelrs** [nylas/nylas-mail#3297]
I’m trying to develop a plugin for Nylas Mail and it’s a bit of a nightmare because of the very low quality of the docs...  
Anyway, despite of the issues, I managed to do a decent amount of work, but now I’m having an issue trying to make a POST request to an external API.  
I found (totally by accident) that the proper way to do that is using the `Task` class, isn’t it?

I have this class:
```
import {Task} from 'nylas-exports';

export default class CreateTodoTask extends Task {
    constructor(toDo) {
        super();
        this.toDo = toDo;
    }
    performLocal() {
        console.log('CreateTodoTask::performLocal()');
    }
    performRemote() {
        console.log('CreateTodoTask::performRemote()');
    };
}
```
And I create the task from a component with:
```
let toDo = {
    list_id: item.get('id'),
    title: this.props.thread.subject,
};
const task = new CreateToDoTask(toDo);
Actions.queueTask(task);
```
By doing that, I get this error:
```
You must queue a `Task` instance. Be sure you have the task registered with the TaskRegistry.  
If this is a task for a custom plugin, you must export a `taskConstructors` array with your  
`Task` constructors in it. You must all subclass the base Nylas `Task`.
```
That's pretty unclear to me 🤔    

My class should be already a `Task` because I’m extending your class… so I assume it’s because I’m missing that step about registering the task with that `TaskRegistry`? And if that's the case, can I have some example about how to do that? I can’t find any decent info about that…

Or maybe I’m missing something obvious? in which case, sorry about that!, but I’m a back-end developer just getting started in modern JS, React, etc… 😅 

_Posting this here as previously [posted](https://nylas-chat.slack.com/archives/nylas-mail-help/p1487706935000670) on Slack without response_

**Comment by plong0** [comment]
I dug into the code and found you need a `taskConstructors: [CreateTodoTask]` in the `module.exports` object.

It's still not working though, even though just before calling `Actions.queueTask(task);`, both `TaskRegistry.isInRegistry(task.constructor.name);` and `task instanceof Task` are returning true!

The console dump of the task object just before the "You must queue a `Task` instance. ..." looks like:

```
task-queue.coffee: 134
Object{
  __constructorName: "CreateTodoTask",
  _rememberedToCallSuper: true,
  id: "local-2277413f-21b0",
  queueState: Object{
    debugStatus: "JUST CONSTRUCTED",
    isProcessing: false,
    localComplete: false,
    localError: null,
    remoteAttempts: 0,
    remoteComplete: false,
    remoteError: null,
    status: null
  },
  sequentialId: null,
  toDo: Object{
    list_id: 1234567890,
    title: "Blah blah blah"
  }
}
```

**Comment by jstejada** [comment]
Hi! In order to fix this you need to register the task in the `TaskRegistry`:

```javascript
// main.es6

import {TaskRegistry} from 'nylas-exports';
import MyTask from './my-task';

export function activate() {
  TaskRegistry.register('MyTask', () => MyTask);
}
```

Let me know if this helps!

**Comment by plong0** [comment]
@jstejada, just tried adding that in, and it is doing the same thing.  As I mentioned, after adding the `taskConstructors` array, when I check `TaskRegistry.isInRegistry(task.constructor.name);` it returns true.

**Comment by plong0** [comment]
It seems like when the task object gets passed from the Nylas plugin into the flux TaskQueue, its class gets lost.

To dig deeper, I expanded the app.asar archive inside the app archive.

**I added some further debug messages into:**
_src/flux/stores/task-queue.js::TaskQueue.prototype.enqueue_

    console.log('(task instanceof Task) == ', (task instanceof Task));
    console.log('task.constructor.name == ', task.constructor.name);
    console.log('TaskRegistry.isInRegistry(task.constructor.name) == ', TaskRegistry.isInRegistry(task.constructor.name));

I repacked app.asar, and reloaded Nylas and tried to fire the action again.

This results in a console _(Activity window > Developer Tools)_ output of:

```
task-queue.coffee:133 [TaskQueue]->enqueue(task) (task instanceof Task) ==  false
task-queue.coffee:134 [TaskQueue]->enqueue(task) task.constructor.name ==  Object
task-queue.coffee:135 [TaskQueue]->enqueue(task) TaskRegistry.isInRegistry(task.constructor.name) ==  false
```
The object dump itself shows as I posted in my previous comment:

    Object {
        __constructorName: "CreateTodoTask",
        _rememberedToCallSuper: true
        ...
    }

**Versus the same dump from the plugin in the main console:**  _(Nylas Mail > Developer Tools)_

```
WunderlistListPickerMenu.jsx [sm]:82 task.constructor.name ==  CreateTodoTask(task instanceof Task) ==  true
WunderlistListPickerMenu.jsx [sm]:83 task.constructor.name ==  CreateTodoTask
WunderlistListPickerMenu.jsx [sm]:84 TaskRegistry.isInRegistry(task.constructor.name) ==  true
```
The object dump itself shows almost the same as the task-queue dump, except with the correct class:

    CreateTodoTask {
        __constructorName: "CreateTodoTask",
        _rememberedToCallSuper: true
        ...
    }


I couldn't find any examples of using `Actions.queueTask` in any other contributed plugins... and as far as I can tell, this plugin is calling it the same as any of the internal_packages.

**Comment by plong0** [comment]
@jstejada can you please re-open?  the suggested solution did not solve the issue.  Please see my last 2 comments detailing my findings.
