### ISSUE TITLE
Signature is not working properly

### ISSUE THREAD

**Issue by zhaoyuxuan** [nylas/nylas-mail#3299]
The signature can't be changed once we delete the old default signature.

##### Are there any related issues?

...

##### What operating system are you using?
...

##### What version of Nylas Mail are you using?
...

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
...

##### Is the issue reproducible with a particular attachment, message, signature, etc?

...

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
...

**Comment by jstejada** [comment]
thanks! merging into #3286
