### ISSUE TITLE
"Nylas Mail is offline" and unread messages counter increasing

### ISSUE THREAD

**Issue by krzema12** [nylas/nylas-mail#3300]
##### Are there any related issues?

I haven't found one.

##### What operating system are you using?
Mac OS X El Capitan 10.11.6

##### What version of Nylas Mail are you using?
Version 1.0.29 (1.0.29)

--

**Bug?**

I've just started Nylas for the first time and configured Gmail. It's downloading messages, so the number of unread messages is growing, but there's a dark-orange box saying that Nylas Mail is offline. It's counterintuitive - how can it be offline when downloading messages? Pressing "Try now" doesn't help, the box is still visible after retrying.

##### Do you have any third-party plugins installed? If so, which ones?
No.

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Not sure.

##### Is the issue reproducible with a particular attachment, message, signature, etc?

Not related.

**Comment by beccanelson** [comment]
This is also my issue. I am able to send and receive messages normally, but I always see the "Nylas Mail is offline" box.

**Comment by jstejada** [comment]
Hi! This issue should be fixed, so I'm closing it for now. 

Let me know if you continue having issues

**Comment by Bramas** [comment]
Hello!! 
I also have the orange box "Nylas Mail is offline" even though I can send and receive email (Gmail only). Nylas Version 1.0.48 (1.0.48)

**Comment by jstejada** [comment]
Oh interesting, yes this might be due to special network configurations. We use https://github.com/sindresorhus/is-online to detect online status

**Comment by Bramas** [comment]
I confirm that using a VPN behind the firewall resolve the issue, no more orange box

**Comment by jacobmischka** [comment]
Also permanently get the orange box on my work network. Would rather not have to use a vpn just for this, could we maybe get a way to disable the notification?

**Comment by jacobmischka** [comment]
I created a PR that should do that, but like I say there I don't think I'm able to build to test it.

**Comment by Bergg** [comment]
I also permanently get the orange box on my work network.

**Comment by Bergg** [comment]
With 2.0.15-0.1 the box is brown..

**Comment by erkage** [comment]
I'm also have the offline box permanently (even after system reboot).
Nylas 2.0.15 / Windows 7 / workplace so i'm behind a firewall.
it's very annoying with this idontknowwhatcolorisit :)

**Comment by jstejada** [comment]
Thanks for the report! we're going ot look into how to fix this
@jacobmischka can you re-submit your PR against latest master?

**Comment by jacobmischka** [comment]
@jstejada Done!

**Comment by jacobmischka** [comment]
With all of the recent changes to the repo, is it possible to build it from source again now?

**Comment by cjernej** [comment]
I also have the offline box continuously showing - really annoying! Running version 2.0.16 on windows 10 (Version 10.0.15063 Build 15063)

**Comment by jacobmischka** [comment]
In the meantime, you can open dev tools and just delete the element.

**Comment by cjernej** [comment]
Thanks! That works for now.Best,Jernej
          
            
            On Apr 20 2017, at 9:19 am, Jacob Mischka <notifications@github.com> wrote:
            
            
              In the meantime, you can open dev tools and just delete the element.
