### ISSUE TITLE
Not able to select default signature

### ISSUE THREAD

**Issue by toshitapandey** [nylas/nylas-mail#3303]
##### What operating system are you using?
MacOS Sierra

##### What version of Nylas Mail are you using?
1.0.29

**Bug?**
##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Not sure, as I use only Gmail

When selecting signature corresponding to my Gmail accounts, Nylas always shows 0 accounts, and never allows to select the account for adding.

**Comment by ykka** [comment]
Same here.

**What operating system are you using?**

MacOS El Capitan 10.11.6

**What version of Nylas Mail are you using?**

1.0.29

**Bug?**

Yes. I am unable to set the default signature for any of my accounts. Clicking on the dropdown item doesn't do anything:

<img width="525" alt="nylas mail nylas mail today at 11 42 16" src="https://cloud.githubusercontent.com/assets/1130636/23338992/b87c8142-fc18-11e6-9d33-d5e44c39f81c.png">

**Comment by cuddylier** [comment]
Was mentioned in #3286 that a fix will be released for this in the next release.

**Comment by jstejada** [comment]
This should be fixed! Let me know if you continue having issues
