### ISSUE TITLE
Option to delete a tag groups and the tags within

### ISSUE THREAD

**Issue by timothyis** [nylas/nylas-mail#3312]
##### Are there any related issues?
Can't find any! (sorry if there are)

##### What operating system are you using?
Mac OSX El Capitan 10.11.6

##### What version of Nylas Mail are you using?
1.0.30

--

**Enhancement**
##### Expected behaviour
When deleting a tag that has tags inside of it, I'd like the option to delete the tag and all tags within.

##### Current behaviour
Deleting a tag with tags inside of it moves those inner tags to the level above. 

![nylas](https://cloud.githubusercontent.com/assets/1695613/23563716/c7939744-003f-11e7-930e-dfea499f47ac.gif)

**Comment by CodeTheory** [comment]
Extending this. This is how GMail deals with multiple label deletions:
![image](https://cloud.githubusercontent.com/assets/1695613/25826516/0e26178a-343f-11e7-97f1-63337a78cd59.png)

**Comment by timothyis** [comment]
Closing this because the project is dead and it's sitting in my issues.
