### ISSUE TITLE
No IMAP option when setting up

### ISSUE THREAD

**Issue by gerardcuadras** [nylas/nylas-mail#3313]
Hi there,

I'm trying to set up an IMAP account in Nylas Mail, but the option doesn't appear.

![image](https://cloud.githubusercontent.com/assets/11849049/23577701/7b3a3f92-00c6-11e7-96f6-cd59e428ca40.png)

I downloaded the Nylas N1 and there's an IMAP option in the setup. I don't know if this is related to the version I downloaded or if it is a bug.

I'm using the macOS version 1.0.30 (1.0.30) in Sierra.

**Comment by 3zero2** [comment]
It's found in the Nylas Mail menu bar > Add custom IMAP Account...
<img width="243" alt="screen shot 2017-03-04 at 23 09 44" src="https://cloud.githubusercontent.com/assets/6965396/23582666/acbcf226-012f-11e7-9b47-52ffef0bb15a.png">

Granted, it would be more user friendly if it was added to the list you showed.

**Comment by gerardcuadras** [comment]
Thanks! You saved my day!

**Comment by hotrush** [comment]
Why need to hide this button??????????????????
