### ISSUE TITLE
Attachments not being forwarded

### ISSUE THREAD

**Issue by toshitapandey** [nylas/nylas-mail#3316]
##### What operating system are you using?
MacOS Sierra

##### What version of Nylas Mail are you using?
1.0.30

**Bug?**
##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Not sure, as I use only Gmail

Attachments are not being forwarded.

**Comment by jstejada** [comment]
Thanks! We're looking into this

**Comment by wr** [comment]
I'm having this issue as well. MacOS Sierra, Nylas Mail 1.0.32

**Comment by cdlangen** [comment]
Me too. Nylas Mail 1.0.45, MacOS Sierra. It is quite problematic.

**Comment by hallamoore** [comment]
Should be fixed in 1.0.48
