### ISSUE TITLE
when will nylas mail client for Linux be ready to download?

### ISSUE THREAD

**Issue by csrgxtu** [nylas/nylas-mail#3319]

**Comment by sachinag** [comment]
In a few weeks, we promise! We are truly sorry for the delay.

**Comment by ryanleesipes** [comment]
Just a .deb or a Snap as well? See snapcraft.io for reference.

**Comment by lindhe** [comment]
I'd be OK with being able to build a buggy alpha from source, before the "real" release... Just sayin'...
