### ISSUE TITLE
Address from Contacts not used

### ISSUE THREAD

**Issue by nedludd** [nylas/nylas-mail#3327]
I have an address "tina_smith@foo.com" in my Gmail contacts.

I start a new message and type "tina" in the address box.  None of the entries presented are in my Google contacts.  Seems like they are pulled from previous messages, including spam... 

The address I was looking for was NOT presented at all.

##### Are there any related issues?

...
Couldn't find any

##### What operating system are you using?
...
macOS Sierra

##### What version of Nylas Mail are you using?
...
1.0.32

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
...No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
...Gmail

##### Is the issue reproducible with a particular attachment, message, signature, etc?

...
![image](https://cloud.githubusercontent.com/assets/17875/23917883/3e3959a8-08c7-11e7-8fcf-d61d32631808.png)

--

**Comment by gplatt** [comment]
I have the same issue. People I email every day do not appear in my list of suggested emails when I type their names, instead I see names I don't recognise at all. I have not emailed one of these people in the list shown for several years if ever, and they do not appear in my google contacts nor my MacBook contact list. 

<img width="420" alt="screenshot 2017-03-29 16 11 56" src="https://cloud.githubusercontent.com/assets/465729/24458876/7c2e6a80-149a-11e7-9df6-95201acea223.png">

**Comment by sachinag** [comment]
We're working on better ranking based on contact strength, please stay tuned!
