### ISSUE TITLE
Nylas Mail for Windows Release Date

### ISSUE THREAD

**Issue by onlineth** [nylas/nylas-mail#3333]
Hello, I can't wait for Nylas Mail to be available on the Windows OS. Currently, when I try to download the app, I'm given this form,

<img src="https://i.imgur.com/msSaFBa.png" height="200">

I was wondering when Nylas Mail will be available for Windows.

**Comment by fakeid30** [comment]
"when it is ready"

**Comment by onlineth** [comment]
@fakeid30 ? I'm not sure what you're saying here. I think my question is pretty clear, when will I be able to download Nylas Mail for Windows. is there a problem with this question?

**Comment by ArchangeGabriel** [comment]
@onlineth Well, “when it is ready”. It means no one knows, though the devs say this is to be counted in weeks rather than months, but they also said that 8 weeks is still less than 2 months for instance. So…

**Comment by onlineth** [comment]
@ArchangeGabriel ok, I'm really not sure why people are giving this issue a thumbs down then. I think this is a decent question to ask especially if like you said, "no one knows"

Is there some other place I'm missing to track the release of this app for Windows? If not, shouldn't there be?!?

**Comment by ArchangeGabriel** [comment]
I think that people reaction is, you’re given a form to be informed of the release. So there is no need to pollute this issue tracker with this question, which is asked again and again (also for Linux builds) by people.

So the answer to this is, we don’t know, just subscribe to the notifications email you’re proposed!

**Comment by onlineth** [comment]
@ArchangeGabriel ok (don't know how many/where it's been asked for the Windows build but I'll take your word for it). Also, I don't think asking for when the release of a Windows build is by any means polluting the issue tracker. I've been waiting as long as you have ("8 weeks" it sounds like) and just wanted an update/propose date of release.

**Comment by sachinag** [comment]
We have been burned by giving a date in the past so we really try not to going forward. 

I'll be honest and admit that we have not met the date we were aiming for in the past. We want to get it right, and not put something out there that is obviously broken. Electron helps a lot but there is still a lot of platform-specific work that had to be done. 

As we've said, we think this is a matter of weeks not months, but we want to have something awesome when it is released into the wild. 

I'm gonna close this issue but we do appreciate everyone who is eager for us to release - we are too!

**Comment by onlineth** [comment]
Thanks guys, my new favorite Windows email client!
