### ISSUE TITLE
Nylas marks my reads as others' read receipts

### ISSUE THREAD

**Issue by ericmjl** [nylas/nylas-mail#3339]
I have noticed a bug in the latest version (Version 1.0.45 (1.0.45)) of Nylas.

I have "Open Tracking" enabled. After I send an email to X, I then open the email in my own Sent folder (doesn't have to be Sent, it can be another folder). Nylas will register my opening of the email as being from the other person. 

I think this is a clear bug; with "Open Tracking", it shouldn't be tracking opens from my own Nylas app.

Additionally, I have found that when I open the messages on my own other devices (e.g. Inbox on iOS), it will also register as "the other party opening my message".

##### Are there any related issues?
I have not found other related issues, though I admit I might be using the wrong keywords to search!

##### What operating system are you using?
Mac OS X

##### What version of Nylas Mail are you using?
Latest

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
- Activity List
- Emoji Picker
- Quick Replies
- Translation
- Link Tracking
- Open Tracking

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Not sure

##### Is the issue reproducible with a particular attachment, message, signature, etc?
No specific attachment, message, signature, or other data needed to reproduce this issue.

**Comment by jstejada** [comment]
Hi! Thanks for the report, we're looking into this one!

**Comment by mollierobbert** [comment]
+1. Experiencing the same bug.

**Comment by djungelkraem** [comment]
Still experiencing this on latest ver (2.0.10) although its said to be fixed in ver 1.0.52

**Comment by jstejada** [comment]
this should be fixed now! thanks!
