### ISSUE TITLE
New mail badge not showing

### ISSUE THREAD

**Issue by ASAPHAANING** [nylas/nylas-mail#3340]
I don't know whether this is per design or not, or maybe it has not been implemented yet, but I do not see unread mail badges on the taskbar on any DE I have tried.

Like the one seen here, on Thunderbird:
[No unread mail badge](http://storage2.static.itmages.com/i/17/0327/h_1490654296_6996985_906ee0a86d.png)

##### Are there any related issues?

No

##### What operating system are you using?
Ubuntu 16.04 64bit

##### What version of Nylas Mail are you using?
Nylas N1 newest from the ubuntu repo.

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No clean install.

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Don't think so, no.

##### Is the issue reproducible with a particular attachment, message, signature, etc?

...

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
...

**Comment by hallamoore** [comment]
Hi there! Merging into #2824

(Also, I think this may be an underlying issue with electron. I don't get badges on any other electron apps, like Slack, either.)
