### ISSUE TITLE
Links broken in mail display if colon (:) in the URL

### ISSUE THREAD

**Issue by jeffmcneill** [nylas/nylas-mail#3346]
Using Nylas N1 1.5.0 under OSX Yosemite 10.10:

I receive links from MediaWiki installs that include a colon in them, such as:

- [https://wikisource.org/wiki/Wikisource_talk:Wikilivres](https://wikisource.org/wiki/Wikisource_talk:Wikilivres)

However, the link breaks at the colon, like this:

- [https://wikisource.org/wiki/Wikisource_talk](https://wikisource.org/wiki/Wikisource_talk):Wikilivres

This isn't the case in other email clients.

**Comment by hallamoore** [comment]
Thanks for reporting! Merging with #2775
