### ISSUE TITLE
Nylas Mail (2.0): No IMAP on first start

### ISSUE THREAD

**Issue by enoversum** [nylas/nylas-mail#3352]
Hi there,

I just thought it'd take it to test, the new Mail app from Nylas, but got stuck on adding my IMAP accounts, since there was no such option on the initial starting screen which requests you to add an e-mail account. 
I only got behind it by browsing Google for it, finding your new documentation and then adding in a bogus Gmail account, so I could actually get to the overview screen and head to the menu bar to access the relevant option to add an IMAP account, finally. Sigh. Couldn't that be a bit easier?

All the best

Eno

**Comment by behzadsh** [comment]
There's a menu named `Add Custom IMAP account` (on mac under nylas mail menu).

**Comment by enoversum** [comment]
@behzadsh Yes, if you read my initial post thoroughly, you would have noticed that I obviously know about it. 
My problem is that you first _have_ to add some other type of account, if you want to add one or not, because you only get past the 'Create account' without IMAP option by adding any of the suggested account types, and then can add an IMAP account through the menu option. IMAP as one of the main options would probably easy to be re-implemented I'd assume, reducing the hassle for IMAP users.

**Comment by jstejada** [comment]
Hi all! We will fix this on our next release!

**Comment by jstejada** [comment]
This should be fixed in the latest release!
