### ISSUE TITLE
Not able to forward the attachment on forward or reply for an email.

### ISSUE THREAD

**Issue by siddhant-mohan** [nylas/nylas-mail#3353]
##### Are there any related issues?

...

##### What operating system are you using?
... mac os

##### What version of Nylas Mail are you using?
...
latest
--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
... N1 todoist integration

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
...
no
##### Is the issue reproducible with a particular attachment, message, signature, etc?

...

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
...

**Comment by hallamoore** [comment]
Hi, what version of Nylas Mail are you using? Forwarding attachments should have been fixed in 1.0.48.
