### ISSUE TITLE
Nylas Mail "messages in a thread require an IMAP uid to perform an action"

### ISSUE THREAD

**Issue by johnramsden** [nylas/nylas-mail#3355]
I keep getting the following message when I try to move an email from my inbox to a folder.

> We were unable to apply the changes to your thread, please try again! If the error persists, contact support@nylas.com with the error message.Error message: All messages in a thread require an IMAP uid to perform an action

##### What operating system are you using?

Arch Linux

##### What version of Nylas Mail are you using?

Nylas Mail Pro 2.0.8-1

##### Do you have any third-party plugins installed? If so, which ones?

No.

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

I only use fastmail.

##### Does this feature exist in another mail client or tool you use?

No.

**Comment by johnramsden** [comment]
I also recieved this after sending an email and was told my message couldn't be moved to the sent folder.

**Comment by johnramsden** [comment]
Just got this when sending an email:

> Your message successfully sent; however, we had trouble saving your message, "Re: Sunday April 9th", to your Sent folder.
> 
> Error: Message contains bare newlines

**Comment by ryanleesipes** [comment]
Same here, seems to not love IMAP/Fastmail.

**Comment by johnramsden** [comment]
Note, the earlier version of Nylas worked perfectly.

**Comment by jstejada** [comment]
merging into duplicate #3308
