### ISSUE TITLE
Allow System tray icon to be packaged with Linux builds

### ISSUE THREAD

**Issue by mustaqimM** [nylas/nylas-mail#3357]
##### Are there any related issues?

N/A

##### What operating system are you using?
Linux

##### What version of Nylas Mail are you using?
2.0.8

--

**Bug?**
The System tray icon currently looks like this in KDE:
![screenshot_20170411_094420](https://cloud.githubusercontent.com/assets/24436622/24898031/94eb7710-1e9b-11e7-882d-dc0e2074f02c.png)

 The notification icons in `https://github.com/nylas/nylas-mail/tree/master/internal_packages/system-tray/assets/linux` should be made available so that it can be changed with programs like [Hardcode-Tray](https://github.com/bil-elmoussaoui/Hardcode-Tray)

**Feature Request?**

Provide System tray icons with the build.

**Comment by bil-elmoussaoui** [comment]
@mustaqimM It can already be changed by Hardcode-Tray :)  At least, it was the case the last time i tried nylas

**Comment by mustaqimM** [comment]
@bil-elmoussaoui It can't anymore, the icons are only available and can only be changed at build time from what I can see
