### ISSUE TITLE
Is this dead ?

### ISSUE THREAD

**Issue by 2Ben** [nylas/nylas-mail#3364]
No commit since Feb 24th... What's going on ?

**Comment by ArchangeGabriel** [comment]
Apparently, they’ve just released v2.0.8, but they still have to officially announce it (I don’t even know how people have been informed of this release) and release the corresponding source code.

It seems they have adopted an “Android-like” development model: source code releases happen when the corresponding binaries are distributed.

**Comment by 2Ben** [comment]
Oh OK. I've been waiting for the Linux client since it was announced, so I was wondering. OK way and see :) Thanks !

**Comment by ArchangeGabriel** [comment]
The .deb file is available at `http://edgehill.s3.amazonaws.com/2.0.8-3e0b575/linux-deb/x64/NylasMail.deb` and `http://edgehill.s3.amazonaws.com/2.0.8-3e0b575/linux-rpm/x64/NylasMail.rpm` (for other distros, either extract it from those package or wait for official builds). And apparently they have been linux builds for a long time, but just never officially.

**Comment by alberto2000** [comment]
Arch AUR Repo at https://aur.archlinux.org/packages/nylas-mail/

**Comment by ArchangeGabriel** [comment]
Rather https://aur.archlinux.org/packages/nylas-mail-bin.

**Comment by jstejada** [comment]
Hi everyone! Sorry for the confusion. We're doing some re-adjusting with our repos which is why you haven't seen commits on this one. We haven't officially released 2.0.x yet. I'll add you to a waiting list for when we officially release our linux build
