### ISSUE TITLE
[Windows 7] .exe Installer for 2.0.9 Fails with old N1 install active

### ISSUE THREAD

**Issue by jtflynnz** [nylas/nylas-mail#3365]
##### Are there any related issues?

Could not find any

##### What operating system are you using?
Windows 7

##### What version of Nylas Mail are you using?
2.0.9

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No

##### Is the issue reproducible with a particular attachment, message, signature, etc?

No

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
No

--

There is an issue where the installer fails partway through the install if Mail is installed while N1 is still open (I originally thought the test build exe would install alongside N1, but it is treated as an upgrade and removes N1, even when the install fails).

I have attached the log (had to "convert" to .txt for Github, but this is a straight copy of the original log), and the fix is to close N1/restart the installer, but perhaps a check for a running instance would help.

[SquirrelSetup - Copy.log.txt](https://github.com/nylas/nylas-mail/files/914662/SquirrelSetup.-.Copy.log.txt)

**Comment by jstejada** [comment]
thanks for the report! we'll look into it!

**Comment by jstejada** [comment]
@jtflynnz , the issue regarding N1 upgrading to Nylas Mail should be fixed now. See: https://github.com/nylas/nylas-mail/issues/3366#issuecomment-293452858. Is the issue fixed for you now?

However, there seems to be an issue when starting the windows build: #3367

**Comment by jstejada** [comment]
hi @jtflynnz, the windows build has been fixed. If you've downloaded a bad build, you can re-download it from nylas.com/download

**Comment by jtflynnz** [comment]
The installer worked, and Nylas Mail launched fine once the initial issue of closing N1 was finished. I still have the N1 exe, so I will try to test with a newer installer for Mail later this week.

Sent from Nylas Mail<https://n1.nylas.com/link/ca4c7f86243d364c88d91b6a5e21baf43fb75a478b3866d191b0008bd11cfdf6/0?redirect=https%3A%2F%2Fnylas.com%3Fref%3Dn1&r=cmVwbHkrMDA1MzI2ZTNhZDJkZjAxOWI4NTQ0OGQwOWVmNzQ4OGViZDc4NmM0NWU2ZDAwYTk0OTJjZjAwMDAwMDAxMTUwNTg3NTE5MmExNjljZTBkMmQ2NDAwQHJlcGx5LmdpdGh1Yi5jb20=>, the best free email app for work

On Apr 12 2017, at 2:12 am, Juan <notifications@github.com> wrote:

hi @jtflynnz<https://github.com/jtflynnz&r=cmVwbHkrMDA1MzI2ZTNhZDJkZjAxOWI4NTQ0OGQwOWVmNzQ4OGViZDc4NmM0NWU2ZDAwYTk0OTJjZjAwMDAwMDAxMTUwNTg3NTE5MmExNjljZTBkMmQ2NDAwQHJlcGx5LmdpdGh1Yi5jb20=>, the windows build has been fixed. If you've downloaded a bad build, you can re-download it from nylas.com/download

**Comment by jtflynnz** [comment]
The installer worked, and Nylas Mail launched fine once the initial issue of closing N1 was finished. I still have the N1 exe, so I will try to test with a newer installer for Mail later this week.

Sent from Nylas Mail<https://n1.nylas.com/link/ca4c7f86243d364c88d91b6a5e21baf43fb75a478b3866d191b0008bd11cfdf6/0?redirect=https%3A%2F%2Fnylas.com%3Fref%3Dn1&r=bnlsYXMtbWFpbEBub3JlcGx5LmdpdGh1Yi5jb20=>, the best free email app for work

On Apr 12 2017, at 2:12 am, Juan <notifications@github.com> wrote:

hi @jtflynnz<https://github.com/jtflynnz&r=bnlsYXMtbWFpbEBub3JlcGx5LmdpdGh1Yi5jb20=>, the windows build has been fixed. If you've downloaded a bad build, you can re-download it from nylas.com/download

**Comment by jtflynnz** [comment]
The installer worked, and Nylas Mail launched fine once the initial issue of closing N1 was finished. I still have the N1 exe, so I will try to test with a newer installer for Mail later this week.

Sent from Nylas Mail<https://n1.nylas.com/link/ca4c7f86243d364c88d91b6a5e21baf43fb75a478b3866d191b0008bd11cfdf6/0?redirect=https%3A%2F%2Fnylas.com%3Fref%3Dn1&r=bWVudGlvbkBub3JlcGx5LmdpdGh1Yi5jb20=>, the best free email app for work

On Apr 12 2017, at 2:12 am, Juan <notifications@github.com> wrote:

hi @jtflynnz<https://github.com/jtflynnz&r=bWVudGlvbkBub3JlcGx5LmdpdGh1Yi5jb20=>, the windows build has been fixed. If you've downloaded a bad build, you can re-download it from nylas.com/download

**Comment by jstejada** [comment]
This should be fixed with version 2.0.13 which was released today! You should be able to run both N1 and Nylas Mail simultaneously if you want without having issues. Let me know if this works for you!

**Comment by jtflynnz** [comment]
Works like a charm now; both installs are running side-by-side (while I try to provide details to a different issue with mail, haha) Thank you to the team!

**Comment by pussinboot** [comment]
hi, i encountered the same error on windows 10 ltsb having installed n1 previously, so not sure if it is actually fixed?
workaround was deleting n1 folders from both appdata\local and appdata\roaming

attached is my log
[SquirrelSetup.txt](https://github.com/nylas/nylas-mail/files/944429/SquirrelSetup.txt)
