### ISSUE TITLE
EWS Support in NylasMail

### ISSUE THREAD

**Issue by anidotnet** [nylas/nylas-mail#3368]
**Feature Request**

Please support Exchange EWS in NylasMail. Due to security reason most of the company exchange servers don't allow ActiveSync from a desktop client. So EWS support would be great addition to NylasMail. Moreover, majority of the email client supports it like Outlook, Evolution, Thunderbird (via plugin).

**Comment by jprrezende** [comment]
I agree. My company uses Exchange Server, and today I downloaded Nylas Mail and for my surprise I cannot connect to the server. :(
Please support Exchange!!

**Comment by mjuarez** [comment]
Nylas N1 subscriber here. I was surprised the new Nylas Mail also didn't allow for Exchange support. This was the primary reason I used Nylas and subscribed.

**Comment by alberto2000** [comment]
As far as I know they will bring back Exchange support - I really hope they do as also for me it's a main selling feature and why I originally went for paid Pro plan.

**Comment by romulogcerqueira** [comment]
Until this moment, the Exchange support is not active
