### ISSUE TITLE
Put version on installer's names

### ISSUE THREAD

**Issue by mhalano** [nylas/nylas-mail#3370]
The idea here is put the version on filenames of installers and packages available on website. For instance, the DEB package is named ad "NylasMail.deb". The problem is since there's no repository, the only way to find for a new release is downloading the package again and reinstalling, so the version on name helps to see if the version is already installed.

**Comment by ArchangeGabriel** [comment]
As a workaround, you can look at [releases](https://github.com/nylas/nylas-mail/releases/), or the actual download link (which contains the version in its path).

For Mac/Windows, the application is self-updating I think, so this is not really an issue (and probably thus look more clean not to have version in the installer name). For Linux, it should not be an issue anymore once distribution will start packaging it, so not sure wether they will change that or not.

**Comment by mhalano** [comment]
Linux distros which aren't rolling release will have old versions packaged. The solution is create an official repository.
