### ISSUE TITLE
[Windows 7] Email becoming de-synced in large batches in Background

### ISSUE THREAD

**Issue by jtflynnz** [nylas/nylas-mail#3372]
[Version 2.0.10] Issue with Hotmail email (set up using the Office 365 preset account option). EMails are becoming de-synced before my eyes, which scared me at first into thinking that the emails were being batch deleted. THankfully, as shown in screenshots below, it appears these are just being removed from the Nylas Mail database.

I attempted to re-sync by closing and reopening the app, however this caused the issue to reoccur on the remaining emails, desyncing now to a farther back time (se screenshots). I have attached logs in hope this helps.

I have 2 gmail, 1 yahoo, and 1 imap (AOL) account all connected, where the others do not appear to have issues currently. 

Edit: Seems to occur when Nylas window is open int he background, is occuring right this moment as I type.  Is it potentially stealing keyboard focus and running a shortcut to archive emails or something?

##### Are there any related issues?

Potentially #3329  and #2729 , though both were with Yandex

##### What operating system are you using?
Windows 7

##### What version of Nylas Mail are you using?
2.0.10

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Yes, Hotmail (Outlook.com)

##### Is the issue reproducible with a particular attachment, message, signature, etc?

N/A

Nylas Mail (note last email is a few days old, and then 1 email seems to be preserved each month where this occurs):
![image](https://cloud.githubusercontent.com/assets/5449443/24965416/fad9e51c-1f71-11e7-90c4-724b7683c022.png)

Outlook.com (all of my first emails are from just this morning, haha):
![image](https://cloud.githubusercontent.com/assets/5449443/24965556/5d40f0e2-1f72-11e7-817b-286bcd2bec37.png)

Logs are attached:

Latest incident
[11-13_Nylas-Mail-16884.16040.log.txt](https://github.com/nylas/nylas-mail/files/917042/11-13_Nylas-Mail-16884.16040.log.txt)

Just prior
[11-something prior_Nylas-Mail-16884.16040.log.txt](https://github.com/nylas/nylas-mail/files/917043/11-something.prior_Nylas-Mail-16884.16040.log.txt)

**Comment by jtflynnz** [comment]
Still present with 2.0.13; have tried disconnecting and reconnecting the account, but each time seems to exacerbate the issue:

![image](https://cloud.githubusercontent.com/assets/5449443/25027424/8604f510-207a-11e7-98e1-392608ed5e06.png)

**Comment by jstejada** [comment]
Wow this is really bad! Thanks for bringing it up, and for all the details! We'll keep you posted with updates

**Comment by flyingclimber** [comment]
By "desyncing" do you mean that your inboxes don't match what you see in Nylas and?

**Comment by jstejada** [comment]
Do you mean that your emails are disappearing from the inbox?

**Comment by jstejada** [comment]
Also, do you have other accounts added to Nylas Mail?

**Comment by jtflynnz** [comment]
> By "desyncing" do you mean that your inboxes don't match what you see in Nylas and?
> Do you mean that your emails are disappearing from the inbox? And they are still in your inbox in Outlook.com?
Yes, exactly; they are there online (thank goodness, lol, or I'd have lost almost every email since September!), but not in my Nylas Mail inbox.
>Also, do you have other accounts added to Nylas Mail?
Yes, 4 others: 2 Gmail, 1 AOL (I know, haha), and 1 Yahoo (yep, I know on this one too, haha).

**Comment by jtflynnz** [comment]
Can confirm, while attemptin to test the new installer for 2.0.13 (to run N1 and Mail side-by-side), N1 is staying synced with the account while Mail continues to have that gap where emails have disappeared from the inbox (what I keep calling "de-syncing," for lack of a better word).:

N1 inbox:
![image](https://cloud.githubusercontent.com/assets/5449443/25043692/c8940342-20ef-11e7-8a80-239e6f46652d.png)

Mail inbox:
![image](https://cloud.githubusercontent.com/assets/5449443/25044744/4e884674-20f6-11e7-809b-6889104953a0.png)

**Comment by jtflynnz** [comment]
2.0.14 slightly improves the issue, I seem to be receiving most of my new emails now, however it still has the same gap in my emails from my inbox.

**Comment by jstejada** [comment]
Hi @jtflynnz, thanks for the additional info!! Indeed 2.0.14 should fix the issue, but it might be the case that the gap will remain there, and we would need to trigger a re-sync in order to restore it fully. If you want to do this, you can go to `Preferences -> General -> Reset email cache`. 
I'm really sorry for the trouble! Hope this helps!

**Comment by jtflynnz** [comment]
It appears to be working without issue now (post email cache reset), thanks for the hard work! (Also especially thanks for the work on 2.0.13 to allow N1 to remain installed, having both installed is helping me compare things for bug-reporting!)

On Apr 17 2017, at 12:08 pm, Juan <notifications@github.com> wrote:

Hi @jtflynnz<https://github.com/jtflynnz>, thanks for the additional info!! Indeed 2.0.14 should fix the issue, but it might be the case that the gap will remain there, and we would need to trigger a re-sync in order to restore it fully. If you want to do this, you can go to Preferences -> General -> Reset email cache.
I'm really sorry for the trouble! Hope this helps!
