### ISSUE TITLE
Unable to choose sync engine as option

### ISSUE THREAD

**Issue by Zangoran** [nylas/nylas-mail#3376]
##### What operating system are you using?
...
Windows 10

Microsoft Windows [Version 10.0.14393]
##### What version of Nylas Mail are you using?
...
2.0.10
--

When setting up Nylas Mail from the download page (https://www.nylas.com/download/) it does not provide the option to use own personal sync engine. But when setting up Nylas N1 from https://github.com/nylas/nylas-mail/releases/tag/1.5.0 the sync engine option shows up right away. Is this an intended action, or is this a bug?

Also I am wondering, how can I setup the sync engine on CentOS 6? I would rather run the sync engine on a bare metal server than just a vm.

**Comment by alexanderadam** [comment]
@Zangoran regarding personal hosting of the sync engine: there are some Dockerfiles on GitHub for the sync engine as well.

**Comment by Zangoran** [comment]
@alexanderadam Would those files work on CentOS? Thanks!

**Comment by Zangoran** [comment]
@jstejada Could you look into this?

**Comment by Karlsoost** [comment]
Same issue here using the linux .deb package. I understood, that there is an option to use it without any sync-engine, aka. Nylas Basic. How to start the client in that mode?

Thank you,
Heiko

**Comment by Xuanwo** [comment]
The same for 2.0.14

![image](https://cloud.githubusercontent.com/assets/5351546/25086236/0d6211e8-2399-11e7-838d-87c7b7f04e81.png)

**Comment by louis-lau** [comment]
According to [this blog post](https://blog.nylas.com/nylas-mail-is-now-free-8350d6a1044d) they moved everything that the sync engine did to the client itself in nylas basic. It also states that it is only available on Mac at the moment, and that they're working on bringing it to linux and windows.

So I do think this feature was intentionally removed, as we won't need it in the future.

**Comment by Karlsoost** [comment]
Well, I clearly understood, that this is the same software only with different pricings, where the basic one is free. The mentioned blog post is from 17th Jan, where indeed only a Mac version was available. Now the other platforms are available as well, but how to use the basic mode?

**Comment by louis-lau** [comment]
@karlsoost Where do you see that the other platforms are available for nylas basic? I'm seeing "supports Mac" on https://nylas.com/pricing . I think we need a clarification from the developers here.

**Comment by Karlsoost** [comment]
yes, indeed. The related download link shows all plattforms in between:
https://nylas.com/download/

And that was different at the stage of the post, where only Mac was available under that link as far as I remember.

**Comment by ArchangeGabriel** [comment]
So, starting again. Not so far ago, there was only one product: Nylas N1. And only one price tier: Pro/Paid. Nylas N1 relies on a “cloud-based” sync-engine, and you where able to host a free (but limited in features) version of it yourself to have N1 working for free.

In January, they announced Nylas Mail (new mail client, replaces N1) and Nylas Basic (new price tier, free, while Pro stays). At this stage, the situation was as follow:

– Nylas Pro only worked with Nylas N1, and still needs the sync engine. Available for the three OSes.
– Nylas Basic only worked with Nylas Mail, almost no need for a cloud engine. Available only for MacOS.

Last week, Nylas Mail was made available for Linux/Windows. FWIU, this is also the first release which supports Pro. But now, a lot of questions remains. They are here:
https://github.com/nylas/nylas-mail/issues/3256#issuecomment-293562035

I’ve acquired partial answers to some of those points. I’ll update my questions after @grinich expected blog post.

**Comment by Karlsoost** [comment]
Thanks for clarification... so I'll stay patient for now and wait what the outcome will be in the other referenced thread.

**Comment by Karlsoost** [comment]
Any update on this?

Thanks,
Heiko

**Comment by jstejada** [comment]
Hi! This is no longer an option in Nylas Mail 2.0 because it already syncs your mail locally, so setting up a local sync-engine is gratuitous. The only option currently to use Nylas Mail against https://github.com/nylas/sync-engine is to run version 1.5.0

Thanks!
