### ISSUE TITLE
Cannot authenticate with Google mail.

### ISSUE THREAD

**Issue by nirvaat** [nylas/nylas-mail#3389]
With today's update now there is another issue popping up. At random interval it is showing a red alert in bottom left saying "Cannot authenticate with google for "my-email". It is not allowing to get emails, or send emails. This has made it completely unusable. This needs urgent fix.

**Comment by nirvaat** [comment]
This is still happening even after installing the latest update i got today. Please fix these issues. It makes the application useless.

**Comment by behzadsh** [comment]
Have this issue here too. Had this issue since upgrading to version 2.0.*

**Comment by jonathanlaf** [comment]
I had this issue, and it was related to Developer Flag. Have you enabled/disabled it ?

**Comment by nirvaat** [comment]
When nylas email starts automatically it starts in dev Mode every time.
Then when I. Lose it and start it again then it starts in normal mode.

And as you suggested the error appears in dev Mode only. But why it starts
in dev Mode in windows start.

**Comment by eddo78** [comment]
I'm having the same issue and it is not related to debug flags. Any thoughts on how to fix this?
