### ISSUE TITLE
SYNC-ENGINE - How to add mail tracking, et al. to self hosted engine?

### ISSUE THREAD

**Issue by Zangoran** [nylas/nylas-mail#3394]
Title sums it up well. But I was just wondering if it is possible to add the functionality of the mail tracking and snooze and etc. to the self hosted sync engine.

Thanks for your time!

@spang 
@jstejada 
@khamidou 
@grinich

**Comment by grinich** [comment]
Hi @Zangoran -- these plugins aren't built as part of the open source sync engine, but we run a limited version of them for free for all Nylas Mail users. The sync engine is only responsible for syncing mail and with the K2 project (blog post forthcoming) is no longer necessary to run in the cloud.

**Comment by Zangoran** [comment]
@grinich Thanks for the quick reply! My only question now, is that how can a user that is using a self hosted sync-engine be able to use the cloud hosted plugins? Thanks for your time!
