### ISSUE TITLE
Nylas Mail app blinks while syncing

### ISSUE THREAD

**Issue by Bergg** [nylas/nylas-mail#3395]
##### Are there any related issues?

...

##### What operating system are you using?
Fedora 25

##### What version of Nylas Mail are you using?
Nylas Email

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No

##### Is the issue reproducible with a particular attachment, message, signature, etc?

While the app message is "syncing your mailbox..." the interface blinks at high frequency and randomly. It seems related to intermittent creation and deletion of an .sql file in the the .nylas-mail folder at the same frequency.

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
...

**Comment by Bergg** [comment]
And it's taking a very long time to sync the IMAP, a couple of hours already and still not done.

**Comment by alberto2000** [comment]
I created an issue about the neverending/broken syncing bug here but Nylas found it to be obsolete for some reason https://github.com/nylas/nylas-mail/issues/3362

**Comment by Bergg** [comment]
Syncing has now stopped, it took about 3-4h or so to complete. The message at the bottom and the blinking of the Nylas window are annoying but users should probably be warned that it'll end eventually. Closing the bug but something can probably be improved in this sync process ?
