### ISSUE TITLE
Syncing Limits / Storage Limits

### ISSUE THREAD

**Issue by sunjay** [nylas/nylas-mail#3398]
Nylas Mail is currently trying to sync my entire gmail inbox which is quite a bit of data. It's been going for several days and still isn't done. It would be nice if I could enforce some sort of syncing limit or storage limit or something so that it wouldn't take forever. The mail client is barely usable when it's syncing.

**Comment by ronisbr** [comment]
I think this is a dup of #3351

**Comment by jstejada** [comment]
it is! merging it
