### ISSUE TITLE
Is there a way to NOT see a particular label?

### ISSUE THREAD

**Issue by neudefoc** [nylas/nylas-mail#3399]
Hi, I've made a little bit of research and I have not found an answer to that.

The question is that I would love to have Gmail's Categories on my Nylas, so that I could see my important mail right away, and if I want it check the offers and blog updates, separately. 

I think that I can do something like that if I create two labels ("Promotions" and "Blog Updates"), link every email account to that label, and then _filter out those labels_ so I don't have to scroll a lot to find my important mail.

Is there a way to do it? 

THANKS A LOT fellows.

**Comment by jstejada** [comment]
Hi @neudefoc , unfortunately there is currently no way to filter out labels out of the UI. Thanks for the feedback!
