### ISSUE TITLE
Cannot set preference to launch Nylas Mail on startup

### ISSUE THREAD

**Issue by Void97** [nylas/nylas-mail#3401]
Hi,
I'm running Nylas Mail 2.0.14 on KDE Neon 5.9. As you can see, there's no option to "launch on startup"
![screenshot_20170418_115100](https://cloud.githubusercontent.com/assets/15859553/25125031/c3fd6c24-242d-11e7-8570-91ed40ff23bd.png)
(I have `libappindicator1` installed).

I tried to manually add a desktop file in ~/.config/autostart/ using --background option, but it resulted in two different instances
![screenshot_20170418_115822](https://cloud.githubusercontent.com/assets/15859553/25125255/702f4e40-242e-11e7-988f-7ebece86f2f2.png)
and one of them (the one launched at startup) is running in dev mode:
![screenshot_20170418_115731](https://cloud.githubusercontent.com/assets/15859553/25125282/8f62d836-242e-11e7-9b7b-a0fb269123be.png)

Do you have any idea? Thanks in advance.

**Comment by jstejada** [comment]
Unfortunately this option is not available on our Linux build. You could do this manually depending on your environment.
Thanks!

**Comment by Void97** [comment]
Yes, I tried to manually launch Nylas Mail at startup by creating a desktop file in ~/.config/autostart, but as I wrote it resulted in multiple instances.

**Comment by kbarralon** [comment]
Same problem here. It worked well before the new version.

**Comment by parsedarweb** [comment]
> @jstejada commented:
> Unfortunately this option is not available on our Linux build. You could do this manually depending on your environment.

What is [this](https://github.com/nylas/nylas-mail/issues/1251#issuecomment-216568640)?
