### ISSUE TITLE
Lots of network error - 502 Bad Gateway

### ISSUE THREAD

**Issue by wblondel** [nylas/nylas-mail#3405]
Hi,

I can't login or register, both on the app and the website, because of these errors.
![image](https://cloud.githubusercontent.com/assets/7508531/25135472/bffa3510-2452-11e7-9275-1bde065ac4c7.png)

**Comment by lenarddome** [comment]
Hello,
I got the following error, i think it is the same:

```
Could not reach Nylas. Please try again or contact
support@nylas.com if the issue persists.
(https://billing.nylas.com/static/fonts/avenir-next-regular.woff:502)
```
or sometimes
```
(https://billing.nylas.com/static/fonts/avenir-next-thin.ttf:502)
```

**Comment by artex-files** [comment]
Same here on both Windows and Linux.

**Comment by bpicori** [comment]
Same here on Ubuntu 16.04

**Comment by ephoras** [comment]
Besides the Errors at hand i also get 
"Cannot authenticate Nylas Mail Cloud Services with ***@gmail.com"

Ans my mails won't get sent. As active as this threat is, is this a current Problem? Or persistent?

Using Mac Sierra 10.12.4

**Comment by ukaric** [comment]
Passed the 502 on starting up. I get this.

![2017-04-18 2](https://cloud.githubusercontent.com/assets/9012882/25136348/0cb4726a-2455-11e7-869f-ac98267f7bfc.png)

**Comment by JohnnyR030T** [comment]
##### What operating system are you using?

Same error in both Windows 10 Pro x64 Ver1703 and also in Ubuntu x64 ver17.04

##### What version of Nylas Mail are you using?

Just downloaded it here 10 minutes ago...
https://billing.nylas.com/download
Looks like the Windows exe file is version 2.0.15.0
File size of the exe is 119MB

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?

No, no third party plugins.

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

I have not had a chance to set any of this up yet. The app will not even open.
I have logged into my email from chrome browser with no problems. Email is not experiencing issues.
I am not using a VPN.

##### Is the issue reproducible with a particular attachment, message, signature, etc?


![nylas_error](https://cloud.githubusercontent.com/assets/2913985/25136122/169092e2-2422-11e7-9749-1c25ef102534.gif)

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
...

**Comment by ukaric** [comment]
@JohnnyR030T  Try running the app as admin should prompt you to add it to firewall exception after that it should be able to connect and you can log-in from there.

**Comment by gugakatsi** [comment]
+1 , same issue on linux mint sarah

**Comment by ferlanero** [comment]
+1 , I have exactly the same issue on Ubuntu 16.04 LTS

**Comment by JohnnyR030T** [comment]
@ukaric Thanks, but still getting same error when running as Administrator. I also tried adding Nylas.exe to Windows firewall manually and still no go. Also, made sure that Win10 Apps and features section is allowing all applications and not just Windows store apps. Tried running Nylas Mail as sudo on my laptop which is running Ubuntu 17.04 and have same exact error as on Win10 pro.

**Comment by JohnnyR030T** [comment]
I'm convinced this has to do with their servers. I'm going to just give it a few hours since they basically just released and see if it doesn't resolve itself. Seems to me it's still pointing to the billing servers for Nylas pro.

**Comment by ferlanero** [comment]
But I have a Nylas N1 Pro account, so I think I need to connect to those billing servers. Or I have to remain using Nylas N1, or what? The info it isn't clear in any way :(

**Comment by edenzik** [comment]
Hitting this issue as well.

**Comment by franzos** [comment]
Tip of the day: Whenever you experience connectivity issues with your favorite service provider, check their status page. https://status.nylas.com/

<img width="865" alt="screen shot 2017-04-18 at 5 03 18 pm" src="https://cloud.githubusercontent.com/assets/2619225/25137735/ea384fd2-2458-11e7-8f8b-7ec266cfd0ef.png">

**Comment by JohnnyR030T** [comment]
I could not even sign into their website and I am registered there so seems to me they are doing some server side work.

**Comment by jstejada** [comment]
This should be solved by now! Thanks for your patience!
