### ISSUE TITLE
No menu bar in Mint Cinnamon 18.1

### ISSUE THREAD

**Issue by thompsondc** [nylas/nylas-mail#3412]
##### Are there any related issues?

None that I can find - possibly an issue with Cinnamon desktop environment interaction.  Often Mint Cinnamon is setup to put the menu bar at the top of the desktop, even if the application is a window and not full screen.

##### What operating system are you using?
Linux Mint (Cinnamon) 18.1

##### What version of Nylas Mail are you using?
Does not say, but it's whichever version recently became available for Linux, downloadable as the filename NylasMail.deb

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
None - fresh install

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No, it seems to be a client issue, possibly interaction with the desktop environment.

##### Is the issue reproducible with a particular attachment, message, signature, etc?

![screenshot from 2017-04-18 15-11-52](https://cloud.githubusercontent.com/assets/2481359/25148657/99ee9360-2449-11e7-98dd-f937f544b509.png)

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
All desktop applications have a menu bar to show various options similar to File, Edit, View, etc...  Even the screenshot in the auto-email I got with the subject line "Finish setting up Nylas Mail" has a screenshot from the application menu bar in OSX.

**Comment by hassec** [comment]
Hi,    
I am not too familiar with Mint, but I have to hit the Alt key in Gnome to see the menu...    
Maybe that already solves the issue?

**Comment by thompsondc** [comment]
I believe it's a Gnome-derivative.  I just tried it, and you're correct.  Alt displays the menu.  This is the first application I've seen this behavior on.  I'll have to see if it applies to more applications.  Thanks.
