### ISSUE TITLE
Nylas won't launch even after re-downloading the application

### ISSUE THREAD

**Issue by RobertMenke** [nylas/nylas-mail#3414]
##### What operating system are you using?
Mac OSX
...

##### What version of Nylas Mail are you using?
Can't tell, the application won't load and there are no menu bar options.
...

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
I have no 3rd party applications installed.
...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
I previously used gmail.
...

##### Is the issue reproducible with a particular attachment, message, signature, etc?

I took a screen capture with Quicktime, but the file is too large to upload. The steps are basically:

1 - Click on the app icon
2 - Check if any of the normal menu bar options are available (only quit is)
3 - try to show available windows (there are none)
...

--

**Comment by cascornelissen** [comment]
I'm running into the same problem on OSX. The icon is available in the dock and the only menu is `Nylas Mail > Quit`. Tried reinstalling but that didn't fix the problem.

I was using multiple Gmail and IMAP accounts.

**Comment by cascornelissen** [comment]
@RobertMenke, this might be related to https://github.com/nylas/nylas-mail/issues/3343. Deleting the `~/.nylas-mail` directory solves the issue but causes the configuration to be deleted as well.

**Comment by jstejada** [comment]
@RobertMenke @cascornelissen , merging into #3343. You can also just delete `~/.nylas-mail/edgehill.db` instead of having to delete the whole folder.

**Comment by emadow** [comment]
Also had this issue. Resolution worked for me but I had to remove and re-add an account since things were wonky with it.
