### ISSUE TITLE
Cannot install on ubuntu 17.04 using .deb

### ISSUE THREAD

**Issue by ssafaei** [nylas/nylas-mail#3415]
Nothing happens when I click on install in Ubuntu Software window!

##### Are there any related issues?

...

##### What operating system are you using?
Ubuntu 17.04

##### What version of Nylas Mail are you using?
Nylas 2.0

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
...

##### Is the issue reproducible with a particular attachment, message, signature, etc?

...

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
...

**Comment by Grokzen** [comment]
@ssafaei It is a bug/issue in ubuntu not this package. See this as example https://askubuntu.com/questions/904539/cant-install-deb-files-on-ubuntu-gnome-17-04

**Comment by ssafaei** [comment]
Working now! Thanks!
