### ISSUE TITLE
No application icon on Windows 10 taskbar

### ISSUE THREAD

**Issue by drkn** [nylas/nylas-mail#3419]
##### What operating system are you using?
Windows 10 Home

##### What version of Nylas Mail are you using?
2.0.15

**Bug**
There is no app icon on Windows 10 taskbar. App appears as blank sheet.

**Comment by shreebles** [comment]
Can you right-click the blank sheet and open and show us its properties?
Like so?

![image](https://cloud.githubusercontent.com/assets/10732529/25286909/b00ddfb6-26bf-11e7-915b-2e81aaf2dcd7.png)

**Comment by drkn** [comment]
![nylas](https://cloud.githubusercontent.com/assets/140258/25328515/6fd9a860-28d8-11e7-9b62-9ab0e9b7499e.png)

**Comment by shreebles** [comment]
This looks like you're using an older version, or at least, like you had this link since the older version, and it hasn't been updated to reflect recent changes. Can you navigate to 

C:\users\drkn\AppData\Local\**NylasMail**\ and drag nylas.exe to the task bar?

**Comment by drkn** [comment]
You're right this must have been N1 leftover. I've removed old shortcut manually and Windows found the new one which works fine.
