### ISSUE TITLE
Ctrl-Shift-R reloads the app environment instead of replying-all

### ISSUE THREAD

**Issue by joeflateau** [nylas/nylas-mail#3426]
##### What operating system are you using?
Windows 8

##### What version of Nylas Mail are you using?
2.0.15

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
None

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No

##### Is the issue reproducible with a particular attachment, message, signature, etc?

Select any email thread, press ctrl-shift-r. App reloads instead of opening "reply all"

--

**Comment by joeflateau** [comment]
I do see the reply-all input appear for a split second before the app reloads, fwiw.

**Comment by Altalus** [comment]
Same issue here, Windows 10 client.
