### ISSUE TITLE
IMAP, incorrect mapping of Sent

### ISSUE THREAD

**Issue by abojchevski** [nylas/nylas-mail#3428]
##### Are there any related issues?
#3222 

##### What operating system are you using?
Windows

##### What version of Nylas Mail are you using?
2.0.15

**Bug?**
* Old sent emails from my university IMAP account are not mapped to sent mails but they show up under "Folders"
* When sending new emails I get the same error as in #3222. Clicking on "Show Details" doesn't display anything.
* Just as additional info the names of folders on my uni's server are "INBOX.Sent", "INBOX.Drafts", etc. This used to work before and suddenly broke. 

##### Do you have any third-party plugins installed? If so, which ones?
None

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
IMAP

##### Is the issue reproducible with a particular attachment, message, signature, etc?

Reproducible after clean reinstall. Even after removing all temporary and settings related folders.

**Comment by jstejada** [comment]
Thanks for the report! We're going to ship an update that should allow users to fix this. merging into #1457
