### ISSUE TITLE
Not an issue, just a thanks

### ISSUE THREAD

**Issue by joshuaniesler** [nylas/nylas-mail#3430]
Everyday I checked my inbox for that magic email saying Nylas is available for Windows. Today it arrived!

**_Finally_** a client for Windows that connects and syncs with iCloud properly!

A million thanks to the Nylas team and keep up the great work!

Josh.

**Comment by dolanor** [comment]
I don't want to spam, but I want to add to that message (I'm on Linux though), but thanks anyway for that great email app!
I would love to have the same experience on my phone too!

Keep up the good work!
