### ISSUE TITLE
Increase font size throughout the interface

### ISSUE THREAD

**Issue by karanrajpal14** [nylas/nylas-mail#3433]
Would you please consider adding a preference to increase the font size throughout the interface? The current one is a tad bit small and is difficult to read. It's the only issue that's keeping me from using Nylas. I'm probably spoiled by gmail's interface.

**Comment by hamm44** [comment]
I have the same request thanks

**Comment by Havok182** [comment]
Hi, I just stumbled here while I was also searching for solution. I am in windows and I did try other method of scaling workspace in config.json but whenever I click emails the font would resize to orginal. 

Luckily for me I use my monitor on 125% dpi. On windows 10 you can force nylas.exe in compatibility tab of its executable Properties to override the dpi scaling for the application, finally worked like a charm.

**Comment by karanrajpal14** [comment]
No point in bothering with this. Apparently, they aren't supporting the program anymore. Just keep using it until it breaks.
[Source](http://www.omgubuntu.co.uk/2017/06/nylas-mail-is-dead-jim)

**Comment by Havok182** [comment]
Thanks for the info, really enjoyed while it lasted. Big difference I found with other mail client was they were not able to search one of my particular email "subject as keyword" even thunderbird. I could however use gmail web client and Nylas to find email with same subject keyword.
