### ISSUE TITLE
No notification or badge functionality in Windows 10 1607

### ISSUE THREAD

**Issue by shreebles** [nylas/nylas-mail#3455]
First of all **thanks**, for providing a free version of your app for Windows! It's a really decent E-Mail client in a market that is getting increasingly dire.
I have noticed some issues with Nylas mail on 2 separate Windows 10 1607 machines that I'd like to share with you.
**These concern the notifications, which do not work for me.**

When receiving a new mail, the small blue bubble next to the Nylas icon appears in the system tray. That is all. No sound, no toast notification. Opening the action center on Windows 10 shows that no notification was received from Nylas. Notifications are allowed on both test systems and work for other apps. Opening the notification settings for all apps in Windows 10, all apps that send notifications are listed and set to allowed. Nylas Mail is not in the list.

![image](https://cloud.githubusercontent.com/assets/10732529/25285966/6403fac2-26bc-11e7-9b08-4e8c73cb98ab.png)

![image](https://cloud.githubusercontent.com/assets/10732529/25286007/8a099e3e-26bc-11e7-928f-3dd46e206eda.png)

**Autoplay is the first and Telegram is the last item in that list. Nylas Mail isn't even listed.**

![image](https://cloud.githubusercontent.com/assets/10732529/25285917/405d0ef6-26bc-11e7-9458-93eb4705798e.png)

As you can see in the image, notifications are enabled. 
Furthermore you can see that badge settings are enabled for Nylas Mail, but they have no effect on the program at all. I would expect some change either in the system tray or the task bar icon when changing this setting, but it always looks the same and the only mail notification I get is a little blue bubble in the system tray.

##### What operating system are you using?
Windows 10 Version 1607, Build 14393.1066 x64 Professional and Enterprise

##### What version of Nylas Mail are you using?
2.0.16

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
n1-avatars v0.1.0

(but only on one machine and the issue occurs on both)

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Only one IMAP provider on both setups

##### Is the issue reproducible with a particular attachment, message, signature, etc?

...

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
Outlook, Windows 10 Mail, Thunderbird, Rambox all send toast notifications

**Comment by shreebles** [comment]
Now working with **Nylas Version 2.0.18**.
Thanks, can be closed!

![image](https://cloud.githubusercontent.com/assets/10732529/25353891/1e5c3472-2931-11e7-828f-7443e11477d4.png)

**Comment by artem-leonov** [comment]
@shreebles Do you have notifications in a notification center? Because I haven't

**Comment by shreebles** [comment]
@artem-leonov actually yes, new mail notifications do show up for me when opening Action Center by pressing Windows+A.
However, it seems they are not persistent, as they disappear after the toast notification faded. Strange...

**Comment by artem-leonov** [comment]
@shreebles Confirm, same issue. But, I think, it's need to create another issue

**Comment by artem-leonov** [comment]
@shreebles I was opened #3475
