### ISSUE TITLE
High CPU usage in linux. Battery draining.

### ISSUE THREAD

**Issue by LiquidO2** [nylas/nylas-mail#3459]
Nylas mail is causing super high cpu usage. 
I am sure it is Nylas mail as cpu usage gets high as soon as I open it and goes down when it is closed. 
It is also causing massive battery draining but I guess that is the result of high cpu usage.

**App information:**
      version: 2.0.18-1
      plugins: no plugin installed except the default ones.

**System information:**
      OS: Manjaro 17.0.1 Gellivara
      Kernel: x86_64 Linux 4.9.22-1-MANJARO
      Shell: bash 4.4.12
      Resolution: 1920x1080
      DE: KDE 5.32.0 / Plasma 5.9.4
      WM: KWin
      CPU: Intel Core i7-7500U @ 4x 3.5GHz [56.0°C]
      GPU: Mesa DRI Intel(R) HD Graphics 620 (Kabylake GT2) 
      RAM: 7869MiB

Please ask if any other info is required.

**Comment by LiquidO2** [comment]
*this issue was not there in previous version.

**Comment by alberto2000** [comment]
https://github.com/nylas/nylas-mail/issues/3402

**Comment by helionmelion** [comment]
did u notice a small but constant disk io write from nylas process? is it normal?

**Comment by shreebles** [comment]
@helionmelion I noticed this only in the beginning when Nylas was initially syncing all my mail, but not anymore now that everything has been synced.

**Comment by helionmelion** [comment]
@shreebles here nylas finish sync but disk io continues. I checked with iotop. Disk write only.

**Comment by jstejada** [comment]
merging into #3178

**Comment by mikeymop** [comment]
I updated Fedora 26 today, and Nylas was able to run.
I did fix a lot of SELinux warnings the day before however it did not result in a working application.
