### ISSUE TITLE
Awkward/impossible link creation

### ISSUE THREAD

**Issue by Sgouws** [nylas/nylas-mail#3468]
##### What operating system are you using?
Windows 10

##### What version of Nylas Mail are you using?
2.0.16

-------------------------------------------------------
#### Scenario:
Trying to create a link from a word in the text.
eg. Click here to see cat pics. The word 'here' would be the link.

#### Expected behavior:
I highlight the word, which brings up the 'quick action' menu. I select edit link, type in the link and voilà, the link is created.

#### Actual behavior:
I highlight the word, 'quick menu' pops up, and I start typing. Quick menu disappears after a like a second, making it virtually impossible to manually enter the URL, I am forced to paste it in before the box disappears.

**Comment by Norfavrell** [comment]
Same issue on Linux Arhat 4.10.10-1-ARCH (nylas 2.0.18)

**Comment by Sgouws** [comment]
The issue seems to have been resolved in the latest build. 2.0.32. 

I'm Closing the issue.
