### ISSUE TITLE
inbox never finish syncing 

### ISSUE THREAD

**Issue by luferogo** [nylas/nylas-mail#3472]
##### Are there any related issues?

I think is similar to [3444](https://github.com/nylas/nylas-mail/issues/3444)

##### What operating system are you using?
Windows 10

##### What version of Nylas Mail are you using?
2.0.18
--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No plugins installed.

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
I am testing with a gmail account

##### Is the issue reproducible with a particular attachment, message, signature, etc?

All the setup is the default one.
I can view some new emails, but there is a message indicating "Syncing your mailbox", 
I have left the computer turned on, thinking maybe is because I have a lot of emails, but more of 3 days have passed and the mail is still syncing... I tried restarting the app but with the same results.
No label has been synced, when I click at one, a "Looking for messages..." message is shown.
--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
No

**Comment by theNathanLin** [comment]
I'm experiencing the same issue; Windows 10 Pro 64-bit; 2.0.18. I have a Google Apps and Gmail account that have synced 'Trash', but are stuck in 'In Progress' for All and Spam. It's kept my CPU up at around 30% consistently.

Another computer that I run also has the issue (10 Home; though it's stuck on just Spam).

**Comment by alberto2000** [comment]
See much needed Feature Request for selective Sync https://github.com/nylas/nylas-mail/issues/3402

**Comment by jstejada** [comment]
yes, unfortunately it is expected for sync to take a long time, especially for large mailboxes. merging into #3402
