### ISSUE TITLE
config.json corrupted if computer powers off

### ISSUE THREAD

**Issue by roja45** [nylas/nylas-mail#3481]
##### Are there any related issues?

...

##### What operating system are you using?
Windows 10

##### What version of Nylas Mail are you using?
2.0.18

--

**Bug?**
If the computer powers off, power outage, random windows panic, the config.json becomes corrupted and the only way to reload nylas mail is to hit the reset button, which causes all your email accounts to be lost.
This has happened every time on a power outage, so I assume reproducible.

##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No

##### Is the issue reproducible with a particular attachment, message, signature, etc?

No

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
...

**Comment by Ed-V** [comment]
I had the same issue as well, had my Windows 10 machine suddenly shut off and rebooted into a corrupted config.json file.

**Comment by jstejada** [comment]
thanks for the report! merging into #3382
