### ISSUE TITLE
Error: Unable to delete message

### ISSUE THREAD

**Issue by ZachTheDev** [nylas/nylas-mail#3544]
##### What operating system are you using?
Microsoft Windows [Version 10.0.14393]

##### What version of Nylas Mail are you using?
2.0.32

--

**Bug?**
When trying to delete a email chain the Error pops up: 

![2017-05-14_21-47-02](https://cloud.githubusercontent.com/assets/7672085/26040937/efd21c16-38ee-11e7-96f1-4030f7111fbd.png)

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
It is with my gmail account, but it seems to be a error that could be possible on any account.

##### Is the issue reproducible with a particular attachment, message, signature, etc?

I can't seem to reproduce it

--

**Comment by Vaska** [comment]
i just installed over the weekend and have the same problem above:

mac 10.10
nylas v2.0.32
