### ISSUE TITLE
[BUG] Very annoying config.json bug, currently have over 1500 config.json files

### ISSUE THREAD

**Issue by ZachTheDev** [nylas/nylas-mail#3561]
##### What operating system are you using?
Microsoft Windows [Version 10.0.14393]

##### What version of Nylas Mail are you using?
2.0.32

**Bug?**
Very much so

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No, this is a nylas problem

##### Is the issue reproducible with a particular attachment, message, signature, etc?
Just keep Nylas loaded, and the errors keep rolling in.

**Comment by Zangoran** [comment]
Currently now at over 2500 config.json files.

**Comment by KTsarlz** [comment]
Yea, this is annoying. A lot of people already reported too.
