### ISSUE TITLE
Nylas won't launch/run in Fedora 25 or 26

### ISSUE THREAD

**Issue by rabbittown** [nylas/nylas-mail#3570]
I cannot get Nylas to run at all. I have tried installing the .rpm through Terminal and through the Software app: no difference in result. I have uninstalled, reinstalled, and done everything else I could think of. The app doesn't ever open. At best, "Nylas Mail" comes up at the top left of the screen and the little timer goes around and around for about 15 seconds and then it quits. No loading page, splash page, nothing. I would appreciate any help or suggestions than anyone could offer to get this going. From what I can tell, this mail client would solve a lot of my workflow issues. Also, the .rpm installs fine and I am able to search the app in Activities once that is done - I just can't get it to launch/run.

What operating system are you using?
Latest Fedora 26 (4.11.0-2.fc26.x86_64), but the same thing happened when I had latest Fedora 25. Upgraded to see if it would help (it didn't).

What version of Nylas Mail are you using?
Latest NylasMail.rpm (2.0.32-0.1) but I've also tried with N1.rpm (1.5.0-0.1) - same result.

Do you have any third-party plugins installed? If so, which ones?
No.

**Comment by mikeymop** [comment]
This seems to be working now for me. I updated Fedora last night and it seems to run today.
I did fix a lot of SELinux warnings for Nylas the past few days, however they did not result in a running application.

**Comment by rabbittown** [comment]
It is now suddenly working. Thanks for replying @mikeymop!
