### ISSUE TITLE
cannot delete emails and delete button missing

### ISSUE THREAD

**Issue by abhazelton** [nylas/nylas-mail#3594]
Hello all,

Really liking Nylas Mail so far, been using it for a couple months now.

**OS**: elementary Loki (Ubuntu 16.04.2 LTS)
**Nylas Mail version**: 2.0.10

**Summary of issue**: On some IMAP accounts, there is no delete button available (as in not even displayed) when viewing a message, and there is no response to pressing the 'delete' key either.

**More details**: I just moved my websites to a new server and this was not an issue before.  So, it appears to be happening only with certain server configurations, and gmail is not affected, either.  I'm not sure how to troubleshoot it as the actual account configuration is set up just fine and everything else works.  The previous host was with GoDaddy, and the new one is DreamHost.  I'm using their secure connections to the mail server.

I'm pasting below a snip from the error log.  It is complaining repeatedly about an authentication error, and yet I am receiving emails and have checked that it is in fact correct.  In addition, I cannot create folders and when Nylas tries to create a 'snooze' category it logs getting the same error.

---------------------------

```
{"host":"aaron-desktop","timestamp":"2017-06-22T03:02:54.237Z","payload":{"fingerprint":["{{ default }}","sync loop","Error: Authentication failed."],"rateLimit":{"ratePerHour":30,"key":"SyncError:SyncLoop:Error: Authentication failed."},"pluginIds":[]}}
{"host":"aaron-desktop","timestamp":"2017-06-22T03:02:54.237Z","payload":"{ Error: Error: Authentication failed.\n    at NylasError (errors.es6:1:8)\n    at IMAPAuthenticationError (imap-errors.es6:29:5)\n    at convertImapError (imap-errors.es6:142:15)\n    at wrappedReject (imap-connection.es6:245:34)\n    at Connection.onErrored (imap-connection.es6:254:11)\n    at emitOne (events.js:101:20)\n    at Connection.emit (events.js:188:7)\n    at reentry (/usr/share/nylas-mail/resources/app.asar/node_modules/isomorphic-core/node_modules/imap/lib/Connection.js:1610:12)\n    at Connection.checkCaps (/usr/share/nylas-mail/resources/app.asar/node_modules/isomorphic-core/node_modules/imap/lib/Connection.js:1635:22)\n    at Connection._resTagged (/usr/share/nylas-mail/resources/app.asar/node_modules/isomorphic-core/node_modules/imap/lib/Connection.js:1535:22)\n    at Parser.<anonymous> (/usr/share/nylas-mail/resources/app.asar/node_modules/isomorphic-core/node_modules/imap/lib/Connection.js:194:10)\n    at emitOne (events.js:96:13)\n    at Parser.emit (events.js:188:7)\n    at Parser._resTagged (/usr/share/nylas-mail/resources/app.asar/node_modules/isomorphic-core/node_modules/imap/lib/Parser.js:179:10)\n    at Parser._parse (/usr/share/nylas-mail/resources/app.asar/node_modules/isomorphic-core/node_modules/imap/lib/Parser.js:143:16)\n    at Parser._tryread (/usr/share/nylas-mail/resources/app.asar/node_modules/isomorphic-core/node_modules/imap/lib/Parser.js:86:15)\n    at TLSSocket.Parser._cbReadable (/usr/share/nylas-mail/resources/app.asar/node_modules/isomorphic-core/node_modules/imap/lib/Parser.js:57:12)\n    at emitNone (events.js:86:13)\n    at TLSSocket.emit (events.js:185:7)\n    at emitReadable_ (_stream_readable.js:432:10)\n    at emitReadable (_stream_readable.js:426:7)\n    at readableAddChunk (_stream_readable.js:187:13)\n    at TLSWrap.onread (net.js:543:20)\n    at Socket.ondata (_stream_wrap.js:58:20)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at readableAddChunk (_stream_readable.js:176:18)\n    at TCP.onread (net.js:543:20)\n  message: 'Error: Authentication failed.',\n  userMessage: 'Incorrect IMAP username or password.',\n  statusCode: 401,\n  source: 'authentication' } { fingerprint: [ '{{ default }}', 'sync loop', 'Error: Authentication failed.' ],\n  pluginIds: [] }\n"}
```

-----------------------------

**Comment by FrankKubuntu** [comment]
I have the same issue in 1.0.12 under Linux (Kubuntu 16.04).

I use 2 accounts (emails) at the same provider and no matter in which order I create them it's always the same that has the delete issue.

I create Account #1, the delete button is there and there is a TRASH folder in Mailspring for this account.
I create Account #2, the delete button is not there and there is no TRASH folder in Mailspring for this account.

I was in the process of transferring everything from Thunderbird and I halted. I'm staying with TB until this issue is fixed. I could not find any workaround, including dragging (moving) a msg to the Trash folder, as the folder is missing!

**Comment by abhazelton** [comment]
this is way old..
