### ISSUE TITLE
Stop spamming, read the regulations of GDPR.

### ISSUE THREAD

**Issue by bpabiszczak** [nylas/nylas-mail#3666]
Hi,
 
I haven't heard back from anyone on the team and was wondering if Nylas APIs integrations are of any interest to you?

If it makes sense to talk, let me know how your calendar looks. You can also schedule a time to speak here.

If this is not your department, who is the appropriate person for me to talk to? 

Kristina Oh
Account Executive @ Nylas
(415) 484-3106

Chat with me here.

To unsubscribe from these emails, reply with unsubscribe in the subject line.

On Jun 1, 2018 5:25 PM, "Kristina Oh" <kristina@nylas.com> wrote:
Hi,
 
Nylas can add a lot of value when it comes to integrating email, calendar and contacts into your platform. I'd love to share how we're doing this, and how we've helped our customers save eng time and increase revenue through our APIs.
 
If you'd like to enhance your customer experience, and free up your development time, please book in a time to speak with me via the link in my signature below.

Looking forward to hearing from you! 

Kristina Oh
Account Executive @ Nylas
(415) 484-3106

Chat with me here.

To unsubscribe from these emails, reply with unsubscribe in the subject line.

On May 30, 2018 10:15 PM, "Kristina Oh" <kristina@nylas.com> wrote:
Hi,
  
I hope I'm not bothering you -- could you please get me in contact with the person at YetiForce in charge of engineering or product?

I'd like to share how Nylas can save YetiForce money and time through our email, calendar, and contacts APIs, while driving end user engagement in your platform.

Read how we've helped Pipedrive, Velocify and Leadgenius to do this - We can do the same for YetiForce!

Kristina Oh
Account Executive @ Nylas
(415) 484-3106

Chat with me here.

To unsubscribe from these emails, reply with unsubscribe in the subject line.

On May 28, 2018 6:45 PM, "Kristina Oh" <kristina@nylas.com> wrote:
Hi Pabiszczak,
 
We know it's a pain when your product roadmap stalls because you're fixing bugs for mailbox connections.

Let Nylas do it for you - we power the email, scheduling, and contacts sync for CRMs like Pipedrive, Lever and Infusionsoft though our out of the box integrations, freeing up time for your eng and product team to focus on higher priority items.

Let's chat to see how we can work with YetiForce to do this - you can book in a time to speak in the calendar link below. 

Kristina Oh
Account Executive @ Nylas
(415) 484-3106

Chat with me here.

To unsubscribe from these emails, reply with unsubscribe in the subject line.

On May 24, 2018 8:46 PM, "Kristina Oh" <kristina@nylas.com> wrote:
Hi Pabiszczak,
 
I tried giving you a call a couple of days ago and was hoping we could schedule a time to discuss email, calendar and contacts integration for your current product offering.

Are you the right person to have this conversation with?
 
If not, could you please put me in contact with either your Head of Product and/or Head of Engineering?

Kristina Oh
Account Executive @ Nylas
(415) 484-3106

Chat with me here.

To unsubscribe from these emails, reply with unsubscribe in the subject line.

On May 22, 2018 4:28 PM, "Kristina Oh" <kristina@nylas.com> wrote:
Hi Pabiszczak,
 
My name is Kristina, and I came across your company on my search for platforms that could benefit from our email, calendar and contacts API. Are you the right person to be speaking with about these integration capabilities for YetiForce?
 
Companies like Pipedrive, Velocify, and Infusionsoft currently use our out of the box integrations to access 100% of all mailbox providers (Gmail, Exchange, and IMAP) and provide their customers with direct emailing, scheduling, and contact syncing - saving their eng and product teams up to 18 months of development time.
 
Would love to speak with you on how YetiForce and Nylas can collaborate. When would be a good time to speak?
 
Alternatively, you can book in a time through the link in my signature below!

Looking forward to it. 

Kristina Oh
Account Executive @ Nylas
(415) 484-3106

Chat with me here.

**Comment by khamidou** [comment]
Sorry about this – we've notified our sales team. You shouldn't receive any more emails from us.

Regards,

**Comment by bpabiszczak** [comment]
rly?

> > Hi Pabiszczak,
>  
> Sending one last email to gauge interest in exploring our email, calendar and contacts APIs.
> 
> I know our integrations will add a lot of value to YetiForce, and would love the opportunity to share this with you.
>  
> Any interest on your end in moving the conversation forward? If so, please email me directly or book in a time with me here - https://my.timekit.io/kristina 
> 
> 
> 
> Kristina Oh
> Account Executive @ Nylas
> (415) 484-3106
> 
> Chat with me here.

> Return-path: <kristina@nylas.com>
> Envelope-to: p.blazej@yetiforce.com
> Delivery-date: Thu, 07 Jun 2018 19:03:12 +0200
> Received: from mail by s2.yetiforce.com with spam-scanned (Exim 4.89_1)
>     (envelope-from <kristina@nylas.com>)
>     id 1fQyJY-000GSA-WA
>     for p.blazej@yetiforce.com; Thu, 07 Jun 2018 19:03:10 +0200
> Received: from mail-qt0-f194.google.com ([209.85.216.194])
>     by s2.yetiforce.com with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
>     (Exim 4.89_1)
>     (envelope-from <kristina@nylas.com>)
>     id 1fQyJY-000G7a-QP
>     for p.blazej@yetiforce.com; Thu, 07 Jun 2018 19:03:08 +0200
> Received: by mail-qt0-f194.google.com with SMTP id y31-v6so10554373qty.9
>     for <p.blazej@yetiforce.com>; Thu, 07 Jun 2018 10:03:08 -0700 (PDT)
> DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
>     d=nylas.com; s=google;
>     h=date:from:to:message-id:in-reply-to:subject:mime-version
>     :content-transfer-encoding;
>     bh=W09HWSfaRDEsQsS5Vz1uazZX5qaW9OCcgt5scq0DgYw=;
>     b=N3+Az74mHNxlltG5H1Kce1QAiwBVySobsQLJaUDn1FsYD+knGUQ5d5QY59QCUCK16d
>     Wm24tO3AemtCrqCDFKRRKw0IZxIwjBqOcu/Ythy4Rlhyx9qGzO15CuJIhMAeQ5E1kyE5
>     +qZ5hmDKEoqG1s88jQPdfKtXNUktM4Ya3TEik=
> X-Google-DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
>     d=1e100.net; s=20161025;
>     h=x-gm-message-state:date:from:to:message-id:in-reply-to:subject
>     :mime-version:content-transfer-encoding;
>     bh=W09HWSfaRDEsQsS5Vz1uazZX5qaW9OCcgt5scq0DgYw=;
>     b=N/hi+62GGdbFQsCEAd26MfdKN7zmS8P8Zkb2jaCMw/nnoUw7DCEjyYwpiQ5ApIBI+e
>     T+m44kxc819Qxy9si2UXVF9ZfFm/CwbWddem70Pfr5JvIqWSM4aRmm7pXhaVnioQo1te
>     pkY2lG8q3uIE0FNnU1sm/mPD8Ql0ICOoywp2uBkBQudR9ijQObbVtcL17pvyvZvW4u8t
>     yk3R3cyFG/afcTjA7jb80vvhS2oY0C+cHAXJpxlRnvcUpVbsSJaGw6/QC1xgeWVtKhhN
>     Mq8ERUlT9OOcI8hO0oreHW4D9m7zBan2x1q+X9fAj5E3vmc7tX0sgUOeAbZPWn9Eb+7H
>     Amjw==
> X-Gm-Message-State: APt69E158mRNHz6sdTL6Wo4aaqVvJD61kBURa6XKLCnrpud1ZIUTNClP
>     P8fO/fsmFGpQ5LSyicD2BAw4HA5xAHo=
> X-Google-Smtp-Source: ADUXVKJocMN9/E4iOxZdWdy8MZKb26iLcDEPfePNsFaCwNYUA1FH1AmnsEjV09kA4gyrpOwH/9k7fw==
> X-Received: by 2002:ac8:305a:: with SMTP id g26-v6mr2580672qte.58.1528390986684;
>     Thu, 07 Jun 2018 10:03:06 -0700 (PDT)
> Received: from localhost.localdomain (ec2-54-243-159-132.compute-1.amazonaws.com. [54.243.159.132])
>     by smtp.gmail.com with ESMTPSA id f3-v6sm39596324qtb.51.2018.06.07.10.03.06
>     for <p.blazej@yetiforce.com>
>     (version=TLS1_2 cipher=ECDHE-RSA-AES128-GCM-SHA256 bits=128/128);
>     Thu, 07 Jun 2018 10:03:06 -0700 (PDT)
> Date: Thu, 07 Jun 2018 17:03:05 +0000
> From: Kristina Oh <kristina@nylas.com>
> To: =?UTF-8?B?UGFiaXN6Y3phayBCxYJhxbxlag==?= <p.blazej@yetiforce.com>
> Message-ID: <5b196549bd75f_6ea83f87c01abe4028283e6@melody-workers-2.mail>
> In-Reply-To: <5b175198b210_6ad347579d01272c2@melody-workers-5.mail>
> Subject: Re: Help with email/calendar integrations?
> Mime-Version: 1.0
> Content-Type: multipart/related;
>     boundary="--==_mimepart_5b196549b651b_6ea83f87c01abe40282828e";
>     charset=UTF-8
> Content-Transfer-Encoding: 7bit

**Comment by khamidou** [comment]
Sorry, wires got crossed. That should be fixed now. 

Again, my apologies.
