### ISSUE TITLE
Automatically BCC when sending an email

### ISSUE THREAD

**Issue by slovenianGooner** [nylas/nylas-mail#565]
It would be great if there was an option in the core of the app to add auto bcc or auto cc on composing new email/reply.

**Comment by bengotow** [comment]
Hey! This is a great plugin idea—I've added it to our plugin ideas list here: https://trello.com/c/qslFgMaU/53-automatically-bcc-when-composing-drafts. Feel free to upvote if you've got a Trello account!

**Comment by defaria** [comment]
I have been wanting to do the same thing. I have an extension for gmail that does the auto bcc for me. I was looking through the docs but couldn't find anything related to those fields. Can you give me some hints as to what look for? I could write my own plugin with a few directions.

**Comment by lotvall** [comment]
This would be awesome for dealing with CRM's and compliance etc.

**Comment by kaifeichen** [comment]
+1

**Comment by cybertk** [comment]
+1

**Comment by evaldofelipe** [comment]
+1

**Comment by evaldofelipe** [comment]
+1

**Comment by niklasravnsborg** [comment]
Hey everyone! I'm on it. Will publish later today. 😌

**Comment by niklasravnsborg** [comment]
Here you go: https://github.com/niklasravnsborg/N1-Auto-Recipients
To install just [download the zip](https://github.com/niklasravnsborg/N1-Auto-Recipients/archive/master.zip) and install it via `Install Plugin...` in the plugins preferences inside of N1.

If you like you can give me some feedback on how this could be improved.

Have a nice day! ☺️

**Comment by michael-montano** [comment]
@niklasravnsborg – Can you explain via a ReadMe exactly what your plugin does? My understanding is that it allows users to use Nylas N1's settings pane to set a standard email address that will always be included on the BCC line of all outgoing email.

Is that understanding correct?

**Comment by niklasravnsborg** [comment]
@michael-montano Yep. Thats correct. Great idea, I will add a readme! ☀️

**Comment by cleonido** [comment]
@niklasravnsborg : it looks like this is a global setting? any chance it could be converted to a per-account setting? 

Namely, my suggestion/question is if the client could add a bcc: myname@myaccount1.com when composing a message from myaccount1 vs  add a bcc: myname@myaccount2.com when composing a message from myaccount2

Sorry if I misunderstood!

**Comment by michael-montano** [comment]
Having it work on a per-account basis is the only way I could use it.

**Use case**: I have two accounts on Nylas, my personal Gmail and my work Gmail; the work Gmail is integrated with HubSpot, and I want to track only work-related mail via the Hubspot bcc address.

**Comment by niklasravnsborg** [comment]
@cleonido Yep. I want to do a per-account setting. At the moment it's global.
@michael-montano I also use it for the Hubspot BCC. I always forgot to add it to my mail.

I will try to integrate an account setting as soon as possible. But I'm now a little bit concerned how long I can use Nylas. It says I only have 2 days left in my trail. How do you guys handle the subscription? I love Nylas because of the open and link tracking–is this still possible in the self built version?

**Comment by michael-montano** [comment]
@niklasravnsborg – I *believe* that those features do work on the self-built version. But I intend just to pay once my trial expires. Since you're building a strong extension for the app, I suggest reaching out to Nylas to see whether they'll give you the one-year-for-free deal that early were granted.

Any update on per-account BCC functionality?

**Comment by bengotow** [comment]
Going to re-open this since we've gotten a few more requests for this feature (https://github.com/nylas/N1/issues/3039) and this one accurately reflects the amount of interest in it. Thanks everyone!

**Comment by jackiehluo** [comment]
Another request: https://github.com/nylas/N1/issues/3049

**Comment by frigaut** [comment]
Any progress that I may have missed on this? I am surprised that not many more people actually are requesting this. For me, the per-account bcc is a vital feature.

**Comment by alasaarela** [comment]
The lack of auto-bcc moved me to G Suite mail as of now. It would be great to have it asap. I promise to move back once that is possible. Until then, I will have to use G Suite on my browser with the Hubspot plugin. The plugin posted last summer on this thread prevents me from opening the compose view of emails.

**Comment by christinatangent** [comment]
@niklasravnsborg I just installed your plugin but it seems to have a bug. When enabled, you aren't able to create a new message or reply to any messages.

**Comment by niklasravnsborg** [comment]
@christinatangent Hey! Yes this is pretty old and I'm sure it's not compatible with the current Nylas version. I stopped using Nylas when they dropped the free version.

**Comment by hadifarnoud** [comment]
I also use it for Hubspot. My issue is this bcc is added to all compose emails even if it's not my work email.

it needs to be per account, and it needs an update to work with latest version of Nylas (although I still use N1)
