### ISSUE TITLE
Feature Request: Plugin and theme manager

### ISSUE THREAD

**Issue by sergeyklay** [nylas/nylas-mail#770]
For example like updating process bundles in Sublime, extensions & themes in Thunderbird, etc

**Comment by jstejada** [comment]
hey @sergeyklay, this is definitely needed and we are working on building a package manager for plugins and themes. Thanks!

**Comment by oldhickory30** [comment]
This is a must! Had a theme that I loved, reinstalled Nylas, now I cant find it!

**Comment by bengotow** [comment]
Hey folks—N1 is actually built on apm (the Atom package manager) and already uses it for plugins and themes. We just haven't exposed a convenient API for downloading, installing and updating plugins yet. Stay tuned!

**Comment by sergeyklay** [comment]
:+1:

**Comment by grinich** [comment]
We have this! :)

**Comment by oldhickory30** [comment]
Great what doe mean? Is there an update soon since, I am unable to use Nylas?

**Comment by equinusocio** [comment]
So? How we can send updates to themes?

**Comment by jackiehluo** [comment]
Another request: https://nylas.zendesk.com/agent/tickets/4662
