### ISSUE TITLE
"mailto: links" and "send document via email"-feature from libreoffice opens a nylas frame but does not forward the document into the email

### ISSUE THREAD

**Issue by Feichtmeier** [nylas/nylas-mail#809]
Sadly the mailto: links and "send document via email"-links for example out of libreoffice do not work.
The main frame from nylas opens but that's it. 
I don't know if this is a bug or just not implemented yet! Anyways it would be really great to have that. Keep up the good work. Awesome mail client so far!

**Comment by mbilker** [comment]
Thanks for the idea @Feichtmeier! From what I know, this feature is not implemented and it is not on the Trello board (https://trello.com/b/hxsqB6vx/n1-open-source-roadmap). I look forward to something like this myself as I use LibreOffice on my Linux workstation and laptop.

**Comment by bengotow** [comment]
Hey @Feichtmeier! Do you know what the mail to link is exactly? We support most mailto links but it may be that libreoffice is trying to add an attachment via mailto:, or something else that we don't support.

**Comment by Feichtmeier** [comment]
The first thing I notived is that when I click on a "mailto:guy@email.com"
link on a website and nylas is selected as my default email programm in
ubuntu, nylas is beeing focused if allready opened or opened if not allready
opened but that's it. No "new mail" frame is opened, only the nylas
"mainframe".

And yeah in libreoffice there is a feature to send the document directly out
of libreoffice. :)

> On Dec 28 2015, at 9:21 pm, Ben Gotow &lt;notifications@github.com&gt;
wrote:  

>

> Hey [@Feichtmeier](https://github.com/Feichtmeier)! Do you know what the
mail to link is exactly? We support most mailto links but it may be that
libreoffice is trying to add an attachment via mailto:, or something else that
we don't support.

>

> —  
Reply to this email directly or [view it on GitHub](https://github.com/nylas/N
1/issues/809#issuecomment-167645597).![](https://github.com/notifications/beac
on/AOno1tAnCCbqf6EgZ_SQGhNPuZ9gonvfks5pUZFIgaJpZM4G6d2p.gif)

**Comment by federicoiosue** [comment]
The same issue appears also as follows:

**OS**: Linux Manjaro - Gnome 3.18
**N1 version**: 0.4.10
**Bug description**: 'Send to' contextual menu in Nautilus opens the N1 main window but not the e-mail composer.
**Steps to reproduce:**
- Install the package (https://download.gnome.org/sources/nautilus-sendto/)
- Select a file with Nautilus and then right-click -> Send to

**Comment by bengotow** [comment]
Hey folks! Could someone with access to a linux machine try this in the latest release? I believe we've fixed it.

**Comment by Feichtmeier** [comment]
I could. But what do you mean with latest release? Should I reinstall it with
a freshly downloaded deb? Or is it some dev-release I need to compile or
anything?  
  
Sent from [Nylas N1](https://nylas.com/n1?ref=n1), the extensible, open source
mail client.  
![](https://link.nylas.com/open/9z39bite3bwdbdfaa4n5t8mni/1c9f9a4f693c461296b0
fbb3fe311532)

On Apr. 8 2016, at 8:20 pm, Ben Gotow &lt;notifications@github.com&gt; wrote:  

> Hey folks! Could someone with access to a linux machine try this in the
latest release? I believe we've fixed it.

>

> —  
You are receiving this because you were mentioned.  
Reply to this email directly or [view it on GitHub](https://github.com/nylas/N
1/issues/809#issuecomment-207544878)![](https://github.com/notifications/beaco
n/AOno1qdAFRsa1YPj1MYg2rAENT20YRBHks5p1pxogaJpZM4G6d2p.gif)

**Comment by CaninoDev** [comment]
Has this issue been resolved? 
My use case is as followed:
[LibreOffice] 

Setup Nylas in LibreOffice:

1. Tools->Options->Internet->E-Mail
2. Type in /usr/bin/nylas (I tried to see if there are any commandline options but nylas -?, --help, or man nylas doesn't exist)
3. File->Send->E-Mail Document

Results in an open compose window but with the text of the file location in the body.. not the actual file. 

![example](https://cloud.githubusercontent.com/assets/16412897/16822394/f0b9efe2-4910-11e6-9d3c-f955df9e22bd.png)

**Comment by CaninoDev** [comment]
Any update on this?
