### ISSUE TITLE
Mark message as unread, as opposed to whole thread ("Mark unread from here" in Gmail)

### ISSUE THREAD

**Issue by adeloscope** [nylas/nylas-mail#829]
As opposed to the whole thread.

This is a feature request.

**Comment by jstejada** [comment]
merging into duplicate #705

**Comment by grinich** [comment]
Reopening since this is a Gmail feature we should think about implementing. (Although it's kind of complicated.)

**Comment by caske33** [comment]
@grinich Could we at least have the extra option next to "reply" and "forward" that is also per e-mail instead of per thread/conversation? 

The global "mark unread" can then mark the conversation as unread, while the other one could mark the e-mail.

**Comment by achekroud** [comment]
+1 to this (and bump)

**Comment by jstejada** [comment]
Unfortunately, we won't be implementing this in the short term. Closing for now!
